name: checks
on:
  push:
    branches:
      - 'main'
  pull_request:

enable-email-notifications: true

jobs:
  build:
    name: Build Forgejo Runner
    if: vars.ROLE == 'forgejo-coding'
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/ci:1'
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v5

      - uses: https://data.forgejo.org/actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: validate go version
        run: |
          set -ex
          toolchain=$(grep -oP '(?<=toolchain ).+' go.mod)
          version=$(go version | cut -d' ' -f3)
          if dpkg --compare-versions ${version#go} lt ${toolchain#go}; then
            echo "go version too low: $toolchain >= $version"
            exit 1
          fi

      - run: make lint-check vet

      - run: make build

      - uses: https://data.forgejo.org/actions/upload-artifact@v3
        with:
          name: forgejo-runner
          path: forgejo-runner

  build-unsupported-platforms:
    name: Build unsupported platforms
    if: vars.ROLE == 'forgejo-coding'
    needs: [build]
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/ci:1'
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v5

      - uses: https://data.forgejo.org/actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Validate Go version
        run: |
          set -ex
          toolchain=$(grep -oP '(?<=toolchain ).+' go.mod)
          version=$(go version | cut -d' ' -f3)
          if dpkg --compare-versions ${version#go} lt ${toolchain#go}; then
            echo "go version too low: $toolchain >= $version"
            exit 1
          fi

      - name: Build for Dragonfly/amd64
        run: |
          make clean
          GOARCH="amd64" GOOS=dragonfly make build

      - name: Build for FreeBSD/amd64
        run: |
          make clean
          GOARCH="amd64" GOOS=freebsd make build

      - name: Build for Illumos/amd64
        run: |
          make clean
          GOARCH="amd64" GOOS=illumos make build

      - name: Build for macOS/arm64
        run: |
          make clean
          GOARCH="arm64" GOOS=darwin make build

      - name: Build for NetBSD/amd64
        run: |
          make clean
          GOARCH="amd64" GOOS=netbsd make build

      - name: Build for OpenBSD/amd64
        run: |
          make clean
          GOARCH="amd64" GOOS=openbsd make build

      - name: Build for Windows/amd64
        run: |
          make clean
          GOARCH="amd64" GOOS=windows make build

  runner-exec-tests:
    name: runner exec tests
    if: vars.ROLE == 'forgejo-coding'
    runs-on: lxc-bookworm
    needs: [build]
    steps:

      - uses: https://data.forgejo.org/actions/checkout@v5

      - uses: https://data.forgejo.org/actions/download-artifact@v3
        with:
          name: forgejo-runner

      - run: chmod +x forgejo-runner

      - name: install docker
        run: |
          mkdir /etc/docker
          cat > /etc/docker/daemon.json  <<EOF
          {
            "ipv6": true,
            "experimental": true,
            "ip6tables": true,
            "fixed-cidr-v6": "fd05:d0ca:1::/64",
            "default-address-pools": [
              {
                "base": "172.19.0.0/16",
                "size": 24
              },
              {
                "base": "fd05:d0ca:2::/104",
                "size": 112
              }
            ]
          }
          EOF
          apt-get install -y -qq docker.io

      - name: forgejo-runner exec --enable-ipv6
        run: |
          set -x
          ./forgejo-runner exec --enable-ipv6 --workflows .forgejo/testdata/ipv6.yml
          if ./forgejo-runner exec --workflows .forgejo/testdata/ipv6.yml >& /tmp/out ; then
             cat /tmp/out
             echo "IPv6 not enabled, should fail"
             exit 1
          fi

      - name: forgejo-runner exec --var
        run: |
          set -x
          ./forgejo-runner exec --var MY_VAR=testvariable --workflows .forgejo/testdata/var.yml |& tee /tmp/var.out
          grep --quiet 'Success - Main echo "VAR -> testvariable"' /tmp/var.out

  integration-tests-with-docker:
    name: Run integration tests with Docker (docker-${{ matrix.docker }})
    if: vars.ROLE == 'forgejo-coding'
    runs-on: lxc-bookworm
    needs: [build]
    strategy:
      matrix:
        docker:
          - stable # docker version distributed by Debian
          - latest # latest stable version of docker distributed by Docker
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v5

      - uses: https://data.forgejo.org/actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install required tools
        env:
          DEBIAN_FRONTEND: noninteractive
        # gcc is required for `go test -race`.
        # qemu-user-static and binfmt-support are required for mixed architecture testing.
        run: |
          apt-get install -y -qq \
            make \
            gcc \
            qemu-user-static \
            binfmt-support

      - name: Install Docker
        run: |
          mkdir -p /etc/docker
          cat > /etc/docker/daemon.json  <<EOF
          {
            "ipv6": true,
            "experimental": true,
            "ip6tables": true,
            "fixed-cidr-v6": "fd05:d0ca:1::/64",
            "default-address-pools": [
              {
                "base": "172.19.0.0/16",
                "size": 24
              },
              {
                "base": "fd05:d0ca:2::/104",
                "size": 112
              }
            ]
          }
          EOF
          ./.forgejo/install-docker.sh ${{ matrix.docker }}

      - name: Install LXC
        run: |
          act/runner/lxc-helpers.sh lxc_prepare_environment
          act/runner/lxc-helpers.sh lxc_install_lxc_inside 10.39.28 fdb1

      - name: Run all tests
        env:
          TEST_MUST_SUPPORT_MIXED_ARCH: true
        run: make integration-test

  integration-tests-with-podman:
    name: Run integration tests with Podman
    if: vars.ROLE == 'forgejo-coding'
    runs-on: lxc-trixie
    needs: [build]
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v5

      - uses: https://data.forgejo.org/actions/setup-go@v6
        with:
          go-version-file: go.mod

      # The Debian container produced by lxc-helpers.sh does not match the images provided by the LXC project
      # (https://images.linuxcontainers.org/) and has some problems. systemd is degraded (see `systemctl --failed`) and
      # only systemd-journald.service is active. For running Podman with an unprivileged user, we need at least
      # systemd-logind.service. Without it, it is not possible to log in as an unprivileged user and the user's
      # environment is broken.
      - name: Get systemd-logind working
        run: |
          apt-get install -y \
              dbus \
              libpam-systemd
          systemctl restart systemd-logind.service
          logind_status="$(systemctl is-active systemd-logind.service)"
          if [[ "$logind_status" != "active" ]] ; then
              echo "The status of systemd-logind is '$logind_status' instead of 'active'" >&2
              exit 1
          fi

      - name: Install required tools
        # gcc is required for `go test -race`.
        run: |
          apt-get install -y \
            make \
            gcc

      - name: Install Podman
        run: |
          apt-get install -y \
              podman

      - name: Create unprivileged user 'forgejo' for use with Podman
        run: |
          useradd --create-home --shell /bin/bash forgejo

      - name: Set Podman up
        run: |
          systemctl --user --machine forgejo@ enable --now podman.socket

          podman_status="$(systemctl --user --machine forgejo@ is-active podman.socket)"
          if [[ "$podman_status" != "active" ]] ; then
              echo "The status of podman is '$podman_status' instead of 'active'" >&2
              exit 1
          fi

      - name: Configure `PATH` and `DOCKER_HOST` of unprivileged user
        run: |
          go_home="$(dirname "$(which go)")"
          echo "PATH=\"\$PATH:$go_home\"" >> /home/forgejo/.profile
          echo 'export DOCKER_HOST="unix:///run/user/$(id -u)/podman/podman.sock"' >> /home/forgejo/.profile

      # Running commands as user forgejo in /root leads to weird permission problems.
      - name: Copy project to home of unprivileged user
        run: |
          mkdir -p /home/forgejo/runner
          cp --recursive .* * /home/forgejo/runner
          chown --recursive forgejo:forgejo /home/forgejo/runner

      - name: Run all tests
        run: |
          run0 -u forgejo --chdir=/home/forgejo/runner \
              bash --login -c 'make integration-test'

  validate-mocks:
    name: validate mocks
    if: vars.ROLE == 'forgejo-coding'
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/ci:1'

    steps:
      - uses: https://data.forgejo.org/actions/checkout@v5

      - uses: https://data.forgejo.org/actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: generate mocks
        run: |
          set -ex
          make deps-tools
          make generate
          make fmt

      - name: validate mocks
        run: |
          git diff --ignore-matching-lines='Code generated by mockery.*DO NOT EDIT' --quiet || {
            echo "[ERROR] Please apply the changes mockery suggests:"
            git diff --color=always
            exit 1
          }

  validate-pre-commit:
    name: validate pre-commit-hooks file
    if: vars.ROLE == 'forgejo-coding'
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/ci:1'

    steps:
      - uses: https://data.forgejo.org/actions/checkout@v5

      - name: install pre-commit
        env:
          DEBIAN_FRONTEND: noninteractive
          PIP_ROOT_USER_ACTION: ignore
          PIP_BREAK_SYSTEM_PACKAGES: 1
          PIP_PROGRESS_BAR: off
        run: |
          apt-get update -qq
          apt-get install -y -qq python3-pip
          python3 -m pip install 'pre-commit>=3.2.0'

      - name: validate .pre-commit-hooks.yaml
        run: pre-commit validate-manifest .pre-commit-hooks.yaml

      # Will fail due to `act/runner/testdata/local-action-fails-schema-validation/action/action.yml`
      - name: check pre-commit hook against local action files (should fail)
        continue-on-error: true
        run: |
          pre-commit try-repo --all-files --verbose . forgejo-runner-validate

      - name: check that a bad workflow file doesn't validate (should fail)
        continue-on-error: true
        run: |
          mkdir -p test-repo
          cd test-repo
          git config set advice.defaultBranchName false
          git init --quiet
          mkdir -p .forgejo/workflows
          cp ../act/runner/testdata/local-action-fails-schema-validation/action/action.yml ./
          touch .forgejo/workflows/bad-workflow.yml
          cat > .pre-commit-config.yaml <<EOF
          repos:
            - repo: ..
              rev: ${{ forge.sha }}
              hooks:
                - id: forgejo-runner-validate
          EOF
          git add .
          pre-commit run --all-files --verbose forgejo-runner-validate
