// Code generated by api/gen from gen/polish.json; DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	"strconv"
	"time"

	forgejo "forgejo.org/client-go"
	"github.com/spf13/cobra"
)

func parseOptTime(s string) (*time.Time, error) {
	if s == "" { return nil, nil }
	t, err := time.Parse(time.RFC3339, s)
	if err != nil { return nil, fmt.Errorf("invalid time (RFC3339): %s", s) }
	return &t, nil
}

func timeArg(t *time.Time) time.Time {
	if t == nil { return time.Time{} }
	return *t
}

func newPolishMilestoneCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "milestone",
		Short: "Manage milestones",
		Aliases: []string{"milestones"},
	}
	cmd.AddCommand(newPolishMilestoneListCmd())
	cmd.AddCommand(newPolishMilestoneViewCmd())
	cmd.AddCommand(newPolishMilestoneCreateCmd())
	cmd.AddCommand(newPolishMilestoneEditCmd())
	cmd.AddCommand(newPolishMilestoneCloseCmd())
	cmd.AddCommand(newPolishMilestoneDeleteCmd())
	return cmd
}

// newPolishMilestoneListCmd — List milestones on a repo
func newPolishMilestoneListCmd() *cobra.Command {
	var state string
	var name string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List milestones on a repo",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueGetMilestonesList(context.Background(), owner, repo, state, name, 1, 20)
			if err != nil { return err }
			if len(res) == 0 {
				fmt.Println("no milestones")
				return nil
			}
			for _, it := range res {
				fmt.Printf("#%d %s [%s] %s\n", it.Id, statusSymbol(stateStr(it.State)), stateStr(it.State), it.Title)
			}
			return nil
		},
	}
	cmd.Flags().StringVarP(&state, "state", "s", "open", "milestone state (open/closed/all)")
	cmd.Flags().StringVar(&name, "name", "", "filter by milestone title")
	return cmd
}

// newPolishMilestoneViewCmd — View a milestone
func newPolishMilestoneViewCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "view <ID>",
		Short: "View a milestone",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueGetMilestone(context.Background(), owner, repo, id)
			if err != nil { return err }
			fmt.Printf("#%d %s\n", res.Id, res.Title)
			fmt.Printf("State: %s\n", stateStr(res.State))
			if res.DueOn != nil {
				fmt.Printf("Due: %s\n", timeStr(res.DueOn))
			}
			fmt.Printf("Issues: %d open / %d closed\n", res.OpenIssues, res.ClosedIssues)
			if res.Description != "" {
				fmt.Printf("\n%s\n", res.Description)
			}
			return nil
		},
	}
	return cmd
}

// newPolishMilestoneCreateCmd — Create a new milestone
func newPolishMilestoneCreateCmd() *cobra.Command {
	var description string
	var due string
	var title string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a new milestone",
		RunE: func(cmd *cobra.Command, args []string) error {
			if title == "" { return fmt.Errorf("--title is required") }
			dueVal, err := parseOptTime(due)
			if err != nil { return err }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueCreateMilestone(context.Background(), owner, repo, &forgejo.CreateMilestoneOption{
				Description: description,
				DueOn: dueVal,
				Title: title,
			})
			if err != nil { return err }
			fmt.Printf("Created #%d: %s\n", res.Id, res.Title)
			return nil
		},
	}
	cmd.Flags().StringVarP(&description, "description", "d", "", "milestone description")
	cmd.Flags().StringVar(&due, "due", "", "due date (RFC3339)")
	cmd.Flags().StringVarP(&title, "title", "t", "", "milestone title (required)")
	return cmd
}

// newPolishMilestoneEditCmd — Edit a milestone
func newPolishMilestoneEditCmd() *cobra.Command {
	var description string
	var due string
	var state string
	var title string
	cmd := &cobra.Command{
		Use:   "edit <ID>",
		Short: "Edit a milestone",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dueVal, err := parseOptTime(due)
			if err != nil { return err }
			id, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueEditMilestone(context.Background(), owner, repo, id, &forgejo.EditMilestoneOption{
				Description: description,
				DueOn: dueVal,
				State: state,
				Title: title,
			})
			if err != nil { return err }
			fmt.Printf("Updated #%d: %s\n", res.Id, res.Title)
			return nil
		},
	}
	cmd.Flags().StringVarP(&description, "description", "d", "", "new milestone description")
	cmd.Flags().StringVar(&due, "due", "", "due date (RFC3339)")
	cmd.Flags().StringVar(&state, "state", "", "milestone state (open/closed)")
	cmd.Flags().StringVarP(&title, "title", "t", "", "new milestone title")
	return cmd
}

// newPolishMilestoneCloseCmd — Close a milestone
func newPolishMilestoneCloseCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "close <ID>",
		Short: "Close a milestone",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, _, err = c.Repo.IssueEditMilestone(context.Background(), owner, repo, id, &forgejo.EditMilestoneOption{
				State: "closed",
			})
			if err != nil { return err }
			fmt.Printf("Closed #%d\n", id)
			return nil
		},
	}
	return cmd
}

// newPolishMilestoneDeleteCmd — Delete a milestone
func newPolishMilestoneDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <ID>",
		Short: "Delete a milestone",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, err = c.Repo.IssueDeleteMilestone(context.Background(), owner, repo, id)
			if err != nil { return err }
			fmt.Printf("Deleted milestone #%d\n", id)
			return nil
		},
	}
	return cmd
}

func newPolishReviewCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "review",
		Short: "Create and submit code reviews on a pull request",
	}
	cmd.AddCommand(newPolishReviewCreateCmd())
	cmd.AddCommand(newPolishReviewCommentCmd())
	cmd.AddCommand(newPolishReviewCommentsCmd())
	cmd.AddCommand(newPolishReviewSubmitCmd())
	cmd.AddCommand(newPolishReviewReplyCmd())
	cmd.AddCommand(newPolishReviewResolveCmd())
	cmd.AddCommand(newPolishReviewUnresolveCmd())
	return cmd
}

// newPolishReviewCreateCmd — Create a review on a pull request
func newPolishReviewCreateCmd() *cobra.Command {
	var body string
	var commitId string
	var event string
	cmd := &cobra.Command{
		Use:   "create <PR>",
		Short: "Create a review on a pull request",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			var eventP *forgejo.ReviewStateType
			if event != "" { conv := forgejo.ReviewStateType(event); eventP = &conv }
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.RepoCreatePullReview(context.Background(), owner, repo, index, &forgejo.CreatePullReviewOptions{
				Body: body,
				CommitId: commitId,
				Event: eventP,
			})
			if err != nil { return err }
			fmt.Printf("review #%d created\n", res.Id)
			return nil
		},
	}
	cmd.Flags().StringVar(&body, "body", "", "review summary comment")
	cmd.Flags().StringVar(&commitId, "commit-id", "", "SHA the review applies to")
	cmd.Flags().StringVar(&event, "event", "", "review verdict: APPROVED, REQUEST_CHANGES, or COMMENT; omit to start a pending review")
	return cmd
}

// newPolishReviewCommentCmd — Add a code-anchored comment to a pending review
func newPolishReviewCommentCmd() *cobra.Command {
	var body string
	var newPosition int64
	var oldPosition int64
	var path string
	cmd := &cobra.Command{
		Use:   "comment <PR> <REVIEW>",
		Short: "Add a code-anchored comment to a pending review",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			if body == "" { return fmt.Errorf("--body is required") }
			if path == "" { return fmt.Errorf("--path is required") }
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			id, err := strconv.ParseInt(args[1], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[1]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.RepoCreatePullReviewComment(context.Background(), owner, repo, index, id, &forgejo.CreatePullReviewCommentOptions{
				Body: body,
				NewPosition: newPosition,
				OldPosition: oldPosition,
				Path: path,
			})
			if err != nil { return err }
			fmt.Printf("comment #%d created\n", res.Id)
			return nil
		},
	}
	cmd.Flags().StringVar(&body, "body", "", "comment text")
	cmd.Flags().Int64Var(&newPosition, "new-position", 0, "line on the new (diff head) side, 0 to omit")
	cmd.Flags().Int64Var(&oldPosition, "old-position", 0, "line on the old (diff base) side, 0 to omit")
	cmd.Flags().StringVar(&path, "path", "", "tree path of the commented file")
	return cmd
}

// newPolishReviewCommentsCmd — List the comments of a review (with resolved markers)
func newPolishReviewCommentsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "comments <PR> <REVIEW>",
		Short: "List the comments of a review (with resolved markers)",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			id, err := strconv.ParseInt(args[1], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[1]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.RepoGetPullReviewComments(context.Background(), owner, repo, index, id)
			if err != nil { return err }
			if len(res) == 0 {
				fmt.Println("no comments")
				return nil
			}
			for _, it := range res {
				fmt.Printf("#%d [%t] %s\n", it.Id, it.Resolved, it.Body)
			}
			return nil
		},
	}
	return cmd
}

// newPolishReviewSubmitCmd — Submit a pending review with a verdict
func newPolishReviewSubmitCmd() *cobra.Command {
	var body string
	var event string
	cmd := &cobra.Command{
		Use:   "submit <PR> <REVIEW>",
		Short: "Submit a pending review with a verdict",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			if event == "" { return fmt.Errorf("--event is required") }
			var eventP *forgejo.ReviewStateType
			if event != "" { conv := forgejo.ReviewStateType(event); eventP = &conv }
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			id, err := strconv.ParseInt(args[1], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[1]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.RepoSubmitPullReview(context.Background(), owner, repo, index, id, &forgejo.SubmitPullReviewOptions{
				Body: body,
				Event: eventP,
			})
			if err != nil { return err }
			fmt.Printf("review #%d submitted\n", res.Id)
			return nil
		},
	}
	cmd.Flags().StringVar(&body, "body", "", "review summary comment")
	cmd.Flags().StringVar(&event, "event", "", "review verdict: APPROVED, REQUEST_CHANGES, or COMMENT")
	return cmd
}

// newPolishReviewReplyCmd — Reply to a review comment thread
func newPolishReviewReplyCmd() *cobra.Command {
	var body string
	cmd := &cobra.Command{
		Use:   "reply <PR> <COMMENT-ID>",
		Short: "Reply to a review comment thread",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			if body == "" { return fmt.Errorf("--body is required") }
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			id, err := strconv.ParseInt(args[1], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[1]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.RepoCreatePullReviewCommentReply(context.Background(), owner, repo, index, id, &forgejo.CreatePullReviewCommentReplyOptions{
				Body: body,
			})
			if err != nil { return err }
			fmt.Printf("Replied to comment #%d\n", res.Id)
			return nil
		},
	}
	cmd.Flags().StringVar(&body, "body", "", "reply text")
	return cmd
}

// newPolishReviewResolveCmd — Resolve a review comment conversation
func newPolishReviewResolveCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "resolve <PR> <COMMENT-ID>",
		Short: "Resolve a review comment conversation",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			id, err := strconv.ParseInt(args[1], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[1]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, err = c.Repo.RepoCreatePullReviewCommentResolution(context.Background(), owner, repo, index, id)
			if err != nil { return err }
			fmt.Printf("Resolved #%d\n", id)
			return nil
		},
	}
	return cmd
}

// newPolishReviewUnresolveCmd — Unresolve a review comment conversation
func newPolishReviewUnresolveCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "unresolve <PR> <COMMENT-ID>",
		Short: "Unresolve a review comment conversation",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			id, err := strconv.ParseInt(args[1], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[1]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, err = c.Repo.RepoDeletePullReviewCommentResolution(context.Background(), owner, repo, index, id)
			if err != nil { return err }
			fmt.Printf("Unresolved #%d\n", id)
			return nil
		},
	}
	return cmd
}

func newPolishIssueCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "issue",
		Short: "Manage issues",
		Aliases: []string{"issues"},
	}
	cmd.AddCommand(newPolishIssueListCmd())
	cmd.AddCommand(newPolishIssueViewCmd())
	cmd.AddCommand(newPolishIssueCommentsCmd())
	cmd.AddCommand(newPolishIssueCreateCmd())
	cmd.AddCommand(newPolishIssueCommentCmd())
	cmd.AddCommand(newPolishIssueCloseCmd())
	cmd.AddCommand(newPolishIssueReopenCmd())
	cmd.AddCommand(newIssueLabelCmd())
	return cmd
}

// newPolishIssueListCmd — List issues on a repo
func newPolishIssueListCmd() *cobra.Command {
	var state string
	var labels string
	var q string
	var kind string
	var milestones string
	var since string
	var before string
	var createdBy string
	var assignedBy string
	var mentionedBy string
	var sort string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List issues on a repo",
		RunE: func(cmd *cobra.Command, args []string) error {
			sinceVal, err := parseOptTime(since)
			if err != nil { return err }
			beforeVal, err := parseOptTime(before)
			if err != nil { return err }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueListIssues(context.Background(), owner, repo, state, labels, q, kind, milestones, timeArg(sinceVal), timeArg(beforeVal), createdBy, assignedBy, mentionedBy, 1, 20, sort)
			if err != nil { return err }
			if len(res) == 0 {
				fmt.Println("no issues")
				return nil
			}
			for _, it := range res {
				fmt.Printf("#%d %s [%s] %s\n", it.Number, statusSymbol(stateStr(it.State)), stateStr(it.State), it.Title)
			}
			return nil
		},
	}
	cmd.Flags().StringVarP(&state, "state", "s", "open", "issue state (open/closed/all)")
	cmd.Flags().StringVar(&labels, "labels", "", "comma-separated label names")
	cmd.Flags().StringVar(&q, "q", "", "search issues by string")
	cmd.Flags().StringVar(&kind, "kind", "", "filter by type (issues/pull requests)")
	cmd.Flags().StringVar(&milestones, "milestones", "", "comma-separated milestone names")
	cmd.Flags().StringVar(&since, "since", "", "only issues updated after (RFC3339)")
	cmd.Flags().StringVar(&before, "before", "", "only issues updated before (RFC3339)")
	cmd.Flags().StringVar(&createdBy, "created-by", "", "filter by creator")
	cmd.Flags().StringVar(&assignedBy, "assigned-by", "", "filter by assignee")
	cmd.Flags().StringVar(&mentionedBy, "mentioned-by", "", "filter by mentioned user")
	cmd.Flags().StringVar(&sort, "sort", "", "sort order (oldest, recentupdate, ...)")
	return cmd
}

// newPolishIssueViewCmd — View an issue
func newPolishIssueViewCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "view <INDEX>",
		Short: "View an issue",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueGetIssue(context.Background(), owner, repo, index)
			if err != nil { return err }
			fmt.Printf("#%d %s\n", res.Number, res.Title)
			fmt.Printf("State: %s\n", stateStr(res.State))
			if res.Body != "" {
				fmt.Printf("\n%s\n", res.Body)
			}
			if res.HtmlUrl != "" {
				fmt.Printf("\nView online at %s\n", res.HtmlUrl)
			}
			return nil
		},
	}
	return cmd
}

// newPolishIssueCommentsCmd — List comments on an issue
func newPolishIssueCommentsCmd() *cobra.Command {
	var since string
	var before string
	cmd := &cobra.Command{
		Use:   "comments <INDEX>",
		Short: "List comments on an issue",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			sinceVal, err := parseOptTime(since)
			if err != nil { return err }
			beforeVal, err := parseOptTime(before)
			if err != nil { return err }
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueGetComments(context.Background(), owner, repo, index, timeArg(sinceVal), timeArg(beforeVal))
			if err != nil { return err }
			if len(res) == 0 {
				fmt.Println("no comments")
				return nil
			}
			for _, it := range res {
				fmt.Printf("[%s] %s\n", timeStr(it.CreatedAt), it.Body)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&since, "since", "", "only comments after (RFC3339)")
	cmd.Flags().StringVar(&before, "before", "", "only comments before (RFC3339)")
	return cmd
}

// newPolishIssueCreateCmd — Create a new issue
func newPolishIssueCreateCmd() *cobra.Command {
	var body string
	var title string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a new issue",
		RunE: func(cmd *cobra.Command, args []string) error {
			if title == "" { return fmt.Errorf("--title is required") }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueCreateIssue(context.Background(), owner, repo, &forgejo.CreateIssueOption{
				Body: body,
				Title: title,
			})
			if err != nil { return err }
			fmt.Printf("Created #%d: %s\n", res.Number, res.Title)
			return nil
		},
	}
	cmd.Flags().StringVarP(&body, "body", "b", "", "issue body")
	cmd.Flags().StringVarP(&title, "title", "t", "", "issue title (required)")
	return cmd
}

// newPolishIssueCommentCmd — Comment on an issue
func newPolishIssueCommentCmd() *cobra.Command {
	var body string
	cmd := &cobra.Command{
		Use:   "comment <INDEX>",
		Short: "Comment on an issue",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if body == "" { return fmt.Errorf("--body is required") }
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, _, err = c.Repo.IssueCreateComment(context.Background(), owner, repo, index, &forgejo.CreateIssueCommentOption{
				Body: body,
			})
			if err != nil { return err }
			fmt.Printf("Comment added\n", )
			return nil
		},
	}
	cmd.Flags().StringVarP(&body, "body", "b", "", "comment body (required)")
	return cmd
}

// newPolishIssueCloseCmd — Close an issue
func newPolishIssueCloseCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "close <INDEX>",
		Short: "Close an issue",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, _, err = c.Repo.IssueEditIssue(context.Background(), owner, repo, index, &forgejo.EditIssueOption{
				State: "closed",
			})
			if err != nil { return err }
			fmt.Printf("Closed #%d\n", index)
			return nil
		},
	}
	return cmd
}

// newPolishIssueReopenCmd — Reopen a closed issue
func newPolishIssueReopenCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "reopen <INDEX>",
		Short: "Reopen a closed issue",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			index, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid index: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, _, err = c.Repo.IssueEditIssue(context.Background(), owner, repo, index, &forgejo.EditIssueOption{
				State: "open",
			})
			if err != nil { return err }
			fmt.Printf("Reopened #%d\n", index)
			return nil
		},
	}
	return cmd
}

// NewPolishedCmds returns the descriptor-driven polished command groups
// (gen/polish.json). Root registers these once; adding a group is a
// descriptor edit + regen — no hand-written command file, no root edit.
func NewPolishedCmds() []*cobra.Command {
	return []*cobra.Command{
		newPolishMilestoneCmd(),
		newPolishReviewCmd(),
		newPolishIssueCmd(),
	}
}

