// Code generated by api/gen from gen/parity.yaml; DO NOT EDIT.

package cmd

// CommandToOperation maps each hand-written fj UX command to the swagger
// operationId it must call. It is the machine-checked parity contract
// between the fj CLI and the Rust forgejo-cli: the parity inventory test
// (tests/integration) reads this map, verifies every operationId still
// exists in swagger.json, and verifies the command is implemented in fj.
// When upstream renames/removes an operationId, generation fails before
// the sync PR is pushed. See docs/cli-parity/.

var CommandToOperation = map[string]string{
	"issue close": "issueEditIssue",
	"issue comment": "issueCreateComment",
	"issue create": "issueCreateIssue",
	"issue list": "issueListIssues",
	"issue search": "issueSearchIssues",
	"issue view": "issueGetIssue",
	"pr create": "repoCreatePullRequest",
	"pr list": "repoListPullRequests",
	"pr merge": "repoMergePullRequest",
	"pr view": "repoGetPullRequest",
	"release create": "repoCreateRelease",
	"release list": "repoListReleases",
	"repo fork": "createFork",
	"tag create": "repoCreateTag",
	"user key add": "userCurrentPostKey",
	"version": "getVersion",
	"whoami": "userGetCurrent",
}
