// Code generated by api/gen from gen/polish.json; DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	"strconv"
	"time"

	forgejo "forgejo.org/client-go"
	"github.com/spf13/cobra"
)

func parseOptTime(s string) (*time.Time, error) {
	if s == "" { return nil, nil }
	t, err := time.Parse(time.RFC3339, s)
	if err != nil { return nil, fmt.Errorf("invalid time (RFC3339): %s", s) }
	return &t, nil
}

func newPolishMilestoneCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "milestone",
		Short: "Manage milestones",
		Aliases: []string{"milestones"},
	}
	cmd.AddCommand(newPolishMilestoneListCmd())
	cmd.AddCommand(newPolishMilestoneViewCmd())
	cmd.AddCommand(newPolishMilestoneCreateCmd())
	cmd.AddCommand(newPolishMilestoneEditCmd())
	cmd.AddCommand(newPolishMilestoneCloseCmd())
	cmd.AddCommand(newPolishMilestoneDeleteCmd())
	return cmd
}

// newPolishMilestoneListCmd — List milestones on a repo
func newPolishMilestoneListCmd() *cobra.Command {
	var state string
	var name string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List milestones on a repo",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueGetMilestonesList(context.Background(), owner, repo, state, name, 1, 20)
			if err != nil { return err }
			if len(res) == 0 {
				fmt.Println("no milestones")
				return nil
			}
			for _, it := range res {
				fmt.Printf("#%d %s [%s] %s\n", it.Id, statusSymbol(stateStr(it.State)), stateStr(it.State), it.Title)
			}
			return nil
		},
	}
	cmd.Flags().StringVarP(&state, "state", "s", "open", "milestone state (open/closed/all)")
	cmd.Flags().StringVar(&name, "name", "", "filter by milestone title")
	return cmd
}

// newPolishMilestoneViewCmd — View a milestone
func newPolishMilestoneViewCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "view <ID>",
		Short: "View a milestone",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueGetMilestone(context.Background(), owner, repo, id)
			if err != nil { return err }
			fmt.Printf("#%d %s\n", res.Id, res.Title)
			fmt.Printf("State: %s\n", stateStr(res.State))
			if res.DueOn != nil {
				fmt.Printf("Due: %s\n", timeStr(res.DueOn))
			}
			fmt.Printf("Issues: %d open / %d closed\n", res.OpenIssues, res.ClosedIssues)
			if res.Description != "" {
				fmt.Printf("\n%s\n", res.Description)
			}
			return nil
		},
	}
	return cmd
}

// newPolishMilestoneCreateCmd — Create a new milestone
func newPolishMilestoneCreateCmd() *cobra.Command {
	var description string
	var due string
	var title string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a new milestone",
		RunE: func(cmd *cobra.Command, args []string) error {
			if title == "" { return fmt.Errorf("--title is required") }
			dueVal, err := parseOptTime(due)
			if err != nil { return err }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueCreateMilestone(context.Background(), owner, repo, &forgejo.CreateMilestoneOption{
				Description: description,
				DueOn: dueVal,
				Title: title,
			})
			if err != nil { return err }
			fmt.Printf("Created #%d: %s\n", res.Id, res.Title)
			return nil
		},
	}
	cmd.Flags().StringVarP(&description, "description", "d", "", "milestone description")
	cmd.Flags().StringVar(&due, "due", "", "due date (RFC3339)")
	cmd.Flags().StringVarP(&title, "title", "t", "", "milestone title (required)")
	return cmd
}

// newPolishMilestoneEditCmd — Edit a milestone
func newPolishMilestoneEditCmd() *cobra.Command {
	var description string
	var due string
	var state string
	var title string
	cmd := &cobra.Command{
		Use:   "edit <ID>",
		Short: "Edit a milestone",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dueVal, err := parseOptTime(due)
			if err != nil { return err }
			id, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			res, _, err := c.Repo.IssueEditMilestone(context.Background(), owner, repo, id, &forgejo.EditMilestoneOption{
				Description: description,
				DueOn: dueVal,
				State: state,
				Title: title,
			})
			if err != nil { return err }
			fmt.Printf("Updated #%d: %s\n", res.Id, res.Title)
			return nil
		},
	}
	cmd.Flags().StringVarP(&description, "description", "d", "", "new milestone description")
	cmd.Flags().StringVar(&due, "due", "", "due date (RFC3339)")
	cmd.Flags().StringVar(&state, "state", "", "milestone state (open/closed)")
	cmd.Flags().StringVarP(&title, "title", "t", "", "new milestone title")
	return cmd
}

// newPolishMilestoneCloseCmd — Close a milestone
func newPolishMilestoneCloseCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "close <ID>",
		Short: "Close a milestone",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, _, err = c.Repo.IssueEditMilestone(context.Background(), owner, repo, id, &forgejo.EditMilestoneOption{
				State: "closed",
			})
			if err != nil { return err }
			fmt.Printf("Closed #%d\n", id)
			return nil
		},
	}
	return cmd
}

// newPolishMilestoneDeleteCmd — Delete a milestone
func newPolishMilestoneDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <ID>",
		Short: "Delete a milestone",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil { return fmt.Errorf("invalid id: %s", args[0]) }
			c, owner, repo, err := resolveClient(cmd)
			if err != nil { return err }
			_, err = c.Repo.IssueDeleteMilestone(context.Background(), owner, repo, id)
			if err != nil { return err }
			fmt.Printf("Deleted milestone #%d\n", id)
			return nil
		},
	}
	return cmd
}

// NewPolishedCmds returns the descriptor-driven polished command groups
// (gen/polish.json). Root registers these once; adding a group is a
// descriptor edit + regen — no hand-written command file, no root edit.
func NewPolishedCmds() []*cobra.Command {
	return []*cobra.Command{
		newPolishMilestoneCmd(),
	}
}

