// Code generated by api/gen. DO NOT EDIT.

package forgejo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// OrgGetUserPermissions — Get user permissions in organization
// GET /users/{username}/orgs/{org}/permissions
func (s *UserService) OrgGetUserPermissions(ctx context.Context, username string, org string) (*OrganizationPermissions, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/orgs/%s/permissions", username, org))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result OrganizationPermissions
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// OrgListUserOrgs — List a user's organizations
// GET /users/{username}/orgs
func (s *UserService) OrgListUserOrgs(ctx context.Context, username string, page int, limit int) ([]Organization, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/orgs", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Organization
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserCheckFollowing — Check if one user is following another user
// GET /users/{username}/following/{target}
func (s *UserService) UserCheckFollowing(ctx context.Context, username string, target string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/following/%s", username, target))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// UserCreateToken — Generate an access token for the specified user
// POST /users/{username}/tokens
func (s *UserService) UserCreateToken(ctx context.Context, username string, body *CreateAccessTokenOption) (*AccessToken, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/tokens", username))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result AccessToken
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// UserDeleteAccessToken — Delete an access token from the specified user's account
// DELETE /users/{username}/tokens/{token}
func (s *UserService) UserDeleteAccessToken(ctx context.Context, username string, token string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/tokens/%s", username, token))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// UserGet — Get a user
// GET /users/{username}
func (s *UserService) UserGet(ctx context.Context, username string) (*User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// UserGetHeatmapData — Get a user's heatmap
// GET /users/{username}/heatmap
func (s *UserService) UserGetHeatmapData(ctx context.Context, username string) ([]UserHeatmapData, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/heatmap", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []UserHeatmapData
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserGetTokens — List the specified user's access tokens
// GET /users/{username}/tokens
func (s *UserService) UserGetTokens(ctx context.Context, username string, page int, limit int) ([]AccessToken, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/tokens", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []AccessToken
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserListActivityFeeds — List a user's activity feeds
// GET /users/{username}/activities/feeds
func (s *UserService) UserListActivityFeeds(ctx context.Context, username string, onlyPerformedBy bool, date string, page int, limit int) ([]Activity, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/activities/feeds", username))
	qry := u.Query()
	if onlyPerformedBy != false {
		qry.Set("only-performed-by", fmt.Sprintf("%v", onlyPerformedBy))
	}
	if date != "" {
		qry.Set("date", fmt.Sprintf("%v", date))
	}
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Activity
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserListFollowers — List the given user's followers
// GET /users/{username}/followers
func (s *UserService) UserListFollowers(ctx context.Context, username string, page int, limit int) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/followers", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserListFollowing — List the users that the given user is following
// GET /users/{username}/following
func (s *UserService) UserListFollowing(ctx context.Context, username string, page int, limit int) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/following", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserListGPGKeys — List the given user's GPG keys
// GET /users/{username}/gpg_keys
func (s *UserService) UserListGPGKeys(ctx context.Context, username string, page int, limit int) ([]GPGKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/gpg_keys", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []GPGKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserListKeys — List the given user's public keys
// GET /users/{username}/keys
func (s *UserService) UserListKeys(ctx context.Context, username string, fingerprint string, page int, limit int) ([]PublicKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/keys", username))
	qry := u.Query()
	if fingerprint != "" {
		qry.Set("fingerprint", fmt.Sprintf("%v", fingerprint))
	}
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []PublicKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserListRepos — List the repos owned by the given user
// GET /users/{username}/repos
func (s *UserService) UserListRepos(ctx context.Context, username string, page int, limit int) ([]Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/repos", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserListStarred — The repos that the given user has starred
// GET /users/{username}/starred
func (s *UserService) UserListStarred(ctx context.Context, username string, page int, limit int) ([]Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/starred", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserListSubscriptions — List the repositories watched by a user
// GET /users/{username}/subscriptions
func (s *UserService) UserListSubscriptions(ctx context.Context, username string, page int, limit int) ([]Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/%s/subscriptions", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// UserSearch — Search for users
// GET /users/search
func (s *UserService) UserSearch(ctx context.Context, q string, uid int64, sort string, page int, limit int) (*interface{}, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/users/search"))
	qry := u.Query()
	if q != "" {
		qry.Set("q", fmt.Sprintf("%v", q))
	}
	if uid != 0 {
		qry.Set("uid", fmt.Sprintf("%v", uid))
	}
	if sort != "" {
		qry.Set("sort", fmt.Sprintf("%v", sort))
	}
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}
