// Code generated by api/gen. DO NOT EDIT.

package forgejo

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

// NotifyGetList — List users's notification threads
// GET /notifications
func (s *NotifyService) NotifyGetList(ctx context.Context, all bool, statusTypes []interface{}, subjectType []interface{}, since time.Time, before time.Time, page int, limit int) ([]NotificationThread, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/notifications"))
	qry := u.Query()
	if all != false { qry.Set("all", fmt.Sprintf("%v", all)) }
	if statusTypes != nil { for _, v := range statusTypes { qry.Add("status-types", fmt.Sprintf("%v", v)) } }
	if subjectType != nil { for _, v := range subjectType { qry.Add("subject-type", fmt.Sprintf("%v", v)) } }
	if since != (time.Time{}) { qry.Set("since", fmt.Sprintf("%v", since)) }
	if before != (time.Time{}) { qry.Set("before", fmt.Sprintf("%v", before)) }
	if page != 0 { qry.Set("page", fmt.Sprintf("%v", page)) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("%v", limit)) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []NotificationThread
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// NotifyGetThread — Get notification thread by ID
// GET /notifications/threads/{id}
func (s *NotifyService) NotifyGetThread(ctx context.Context, id int64) (*NotificationThread, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/notifications/threads/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result NotificationThread
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// NotifyNewAvailable — Check if unread notifications exist
// GET /notifications/new
func (s *NotifyService) NotifyNewAvailable(ctx context.Context) (*NotificationCount, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/notifications/new"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result NotificationCount
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// NotifyReadList — Mark notification threads as read, pinned or unread
// PUT /notifications
func (s *NotifyService) NotifyReadList(ctx context.Context, lastReadAt time.Time, all bool, statusTypes []interface{}, toStatus string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/notifications"))
	qry := u.Query()
	if lastReadAt != (time.Time{}) { qry.Set("last_read_at", fmt.Sprintf("%v", lastReadAt)) }
	if all != false { qry.Set("all", fmt.Sprintf("%v", all)) }
	if statusTypes != nil { for _, v := range statusTypes { qry.Add("status-types", fmt.Sprintf("%v", v)) } }
	if toStatus != "" { qry.Set("to-status", fmt.Sprintf("%v", toStatus)) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// NotifyReadThread — Mark notification thread as read by ID
// PATCH /notifications/threads/{id}
func (s *NotifyService) NotifyReadThread(ctx context.Context, id int64, toStatus string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/notifications/threads/%d", id))
	qry := u.Query()
	if toStatus != "" { qry.Set("to-status", fmt.Sprintf("%v", toStatus)) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

