// Code generated by api/gen; DO NOT EDIT.

package forgejo

// Spec metadata recording the exact Forgejo swagger spec this SDK was
// generated from. The CLI reports SpecAPIVersion as its client API level
// (like kubectl's client version) and queries the live server's /version
// for the server side.

const SpecTitle = "Forgejo API"

// SpecVersion is info.version of the swagger.json the SDK was generated from
// (full Forgejo application version, including build metadata).
const SpecVersion = "16.0.0-dev-507-cbafedda0a+gitea-1.22.0"

// SpecAPIVersion is the Gitea REST API compatibility version derived from
// SpecVersion (the +gitea-<v> suffix). This is the API level the SDK maps.
const SpecAPIVersion = "1.22.0"
