// Code generated by api/gen. DO NOT EDIT.

package forgejo

import "time"

type APIError struct {
	Message string `json:"message,omitempty"`
	Url string `json:"url,omitempty"`
}

type APIForbiddenError struct {
	Message string `json:"message,omitempty"`
	Url string `json:"url,omitempty"`
}

type APIInternalServerError struct {
	Message string `json:"message,omitempty"`
	Url string `json:"url,omitempty"`
}

type APIInvalidTopicsError struct {
	InvalidTopics []string `json:"invalidTopics,omitempty"`
	Message string `json:"message,omitempty"`
}

type APINotFound struct {
	Errors []string `json:"errors,omitempty"`
	Message string `json:"message,omitempty"`
	Url string `json:"url,omitempty"`
}

type APIRepoArchivedError struct {
	Message string `json:"message,omitempty"`
	Url string `json:"url,omitempty"`
}

type APIUnauthorizedError struct {
	Message string `json:"message,omitempty"`
	Url string `json:"url,omitempty"`
}

type APIValidationError struct {
	Message string `json:"message,omitempty"`
	Url string `json:"url,omitempty"`
}

type APRemoteFollowOption struct {
	Target string `json:"target,omitempty"`
}

type AccessToken struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Repositories []*RepositoryMeta `json:"repositories,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	Sha1 string `json:"sha1,omitempty"`
	TokenLastEight string `json:"token_last_eight,omitempty"`
}

type ActionArtifact struct {
	ArchiveDownloadUrl string `json:"archive_download_url,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Expired bool `json:"expired,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	RunId int64 `json:"run_id,omitempty"`
	SizeInBytes int64 `json:"size_in_bytes,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type ActionRun struct {
	ScheduleID int64 `json:"ScheduleID,omitempty"`
	ApprovedBy int64 `json:"approved_by,omitempty"`
	CommitSha string `json:"commit_sha,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	Duration *Duration `json:"duration,omitempty"`
	Event string `json:"event,omitempty"`
	EventPayload string `json:"event_payload,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	IndexInRepo int64 `json:"index_in_repo,omitempty"`
	IsForkPullRequest bool `json:"is_fork_pull_request,omitempty"`
	IsRefDeleted bool `json:"is_ref_deleted,omitempty"`
	NeedApproval bool `json:"need_approval,omitempty"`
	Prettyref string `json:"prettyref,omitempty"`
	Repository *Repository `json:"repository,omitempty"`
	Started *time.Time `json:"started,omitempty"`
	Status string `json:"status,omitempty"`
	Stopped *time.Time `json:"stopped,omitempty"`
	Title string `json:"title,omitempty"`
	TriggerEvent string `json:"trigger_event,omitempty"`
	TriggerUser *User `json:"trigger_user,omitempty"`
	Updated *time.Time `json:"updated,omitempty"`
	WorkflowId string `json:"workflow_id,omitempty"`
}

type ActionRunJob struct {
	Attempt int64 `json:"attempt,omitempty"`
	Handle string `json:"handle,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Needs []string `json:"needs,omitempty"`
	OwnerId int64 `json:"owner_id,omitempty"`
	RepoId int64 `json:"repo_id,omitempty"`
	RunId int64 `json:"run_id,omitempty"`
	RunsOn []string `json:"runs_on,omitempty"`
	Status string `json:"status,omitempty"`
	TaskId int64 `json:"task_id,omitempty"`
}

type ActionRunner struct {
	Description string `json:"description,omitempty"`
	Ephemeral bool `json:"ephemeral,omitempty"`
	Id int64 `json:"id,omitempty"`
	Labels []string `json:"labels,omitempty"`
	Name string `json:"name,omitempty"`
	OwnerId int64 `json:"owner_id,omitempty"`
	RepoId int64 `json:"repo_id,omitempty"`
	Status string `json:"status,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	Version string `json:"version,omitempty"`
}

type ActionTask struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DisplayTitle string `json:"display_title,omitempty"`
	Event string `json:"event,omitempty"`
	HeadBranch string `json:"head_branch,omitempty"`
	HeadSha string `json:"head_sha,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	RunNumber int64 `json:"run_number,omitempty"`
	RunStartedAt *time.Time `json:"run_started_at,omitempty"`
	Status string `json:"status,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
	WorkflowId string `json:"workflow_id,omitempty"`
}

type ActionTaskResponse struct {
	TotalCount int64 `json:"total_count,omitempty"`
	WorkflowRuns []*ActionTask `json:"workflow_runs,omitempty"`
}

type ActionVariable struct {
	Data string `json:"data,omitempty"`
	Name string `json:"name,omitempty"`
	OwnerId int64 `json:"owner_id,omitempty"`
	RepoId int64 `json:"repo_id,omitempty"`
}

type Activity struct {
	ActUser *User `json:"act_user,omitempty"`
	ActUserId int64 `json:"act_user_id,omitempty"`
	Comment *Comment `json:"comment,omitempty"`
	CommentId int64 `json:"comment_id,omitempty"`
	Content string `json:"content,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	Id int64 `json:"id,omitempty"`
	IsPrivate bool `json:"is_private,omitempty"`
	OpType string `json:"op_type,omitempty"`
	RefName string `json:"ref_name,omitempty"`
	Repo *Repository `json:"repo,omitempty"`
	RepoId int64 `json:"repo_id,omitempty"`
	UserId int64 `json:"user_id,omitempty"`
}

type ActivityPub struct {
	Xcontext string `json:"@context,omitempty"`
}

type AddCollaboratorOption struct {
	Permission string `json:"permission,omitempty"`
}

type AddTimeOption struct {
	Created *time.Time `json:"created,omitempty"`
	Time int64 `json:"time,omitempty"`
	UserName string `json:"user_name,omitempty"`
}

type AnnotatedTag struct {
	ArchiveDownloadCount *TagArchiveDownloadCount `json:"archive_download_count,omitempty"`
	Message string `json:"message,omitempty"`
	Object *AnnotatedTagObject `json:"object,omitempty"`
	Sha string `json:"sha,omitempty"`
	Tag string `json:"tag,omitempty"`
	Tagger *CommitUser `json:"tagger,omitempty"`
	Url string `json:"url,omitempty"`
	Verification *PayloadCommitVerification `json:"verification,omitempty"`
}

type AnnotatedTagObject struct {
	Sha string `json:"sha,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
}

type Attachment struct {
	BrowserDownloadUrl string `json:"browser_download_url,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DownloadCount int64 `json:"download_count,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Size int64 `json:"size,omitempty"`
	Type_ string `json:"type,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}

type BlockedUser struct {
	BlockId int64 `json:"block_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

type Branch struct {
	Commit *PayloadCommit `json:"commit,omitempty"`
	EffectiveBranchProtectionName string `json:"effective_branch_protection_name,omitempty"`
	EnableStatusCheck bool `json:"enable_status_check,omitempty"`
	Name string `json:"name,omitempty"`
	Protected bool `json:"protected,omitempty"`
	RequiredApprovals int64 `json:"required_approvals,omitempty"`
	StatusCheckContexts []string `json:"status_check_contexts,omitempty"`
	UserCanMerge bool `json:"user_can_merge,omitempty"`
	UserCanPush bool `json:"user_can_push,omitempty"`
}

type BranchProtection struct {
	ApplyToAdmins bool `json:"apply_to_admins,omitempty"`
	ApprovalsWhitelistTeams []string `json:"approvals_whitelist_teams,omitempty"`
	ApprovalsWhitelistUsername []string `json:"approvals_whitelist_username,omitempty"`
	BlockOnOfficialReviewRequests bool `json:"block_on_official_review_requests,omitempty"`
	BlockOnOutdatedBranch bool `json:"block_on_outdated_branch,omitempty"`
	BlockOnRejectedReviews bool `json:"block_on_rejected_reviews,omitempty"`
	BranchName string `json:"branch_name,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DismissStaleApprovals bool `json:"dismiss_stale_approvals,omitempty"`
	EnableApprovalsWhitelist bool `json:"enable_approvals_whitelist,omitempty"`
	EnableMergeWhitelist bool `json:"enable_merge_whitelist,omitempty"`
	EnablePush bool `json:"enable_push,omitempty"`
	EnablePushWhitelist bool `json:"enable_push_whitelist,omitempty"`
	EnableStatusCheck bool `json:"enable_status_check,omitempty"`
	IgnoreStaleApprovals bool `json:"ignore_stale_approvals,omitempty"`
	MergeWhitelistTeams []string `json:"merge_whitelist_teams,omitempty"`
	MergeWhitelistUsernames []string `json:"merge_whitelist_usernames,omitempty"`
	ProtectedFilePatterns string `json:"protected_file_patterns,omitempty"`
	PushWhitelistDeployKeys bool `json:"push_whitelist_deploy_keys,omitempty"`
	PushWhitelistTeams []string `json:"push_whitelist_teams,omitempty"`
	PushWhitelistUsernames []string `json:"push_whitelist_usernames,omitempty"`
	RequireSignedCommits bool `json:"require_signed_commits,omitempty"`
	RequiredApprovals int64 `json:"required_approvals,omitempty"`
	RuleName string `json:"rule_name,omitempty"`
	StatusCheckContexts []string `json:"status_check_contexts,omitempty"`
	UnprotectedFilePatterns string `json:"unprotected_file_patterns,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type ChangeFileOperation struct {
	Content string `json:"content,omitempty"`
	FromPath string `json:"from_path,omitempty"`
	Operation string `json:"operation,omitempty"`
	Path string `json:"path,omitempty"`
	Sha string `json:"sha,omitempty"`
}

type ChangeFilesOptions struct {
	Author *Identity `json:"author,omitempty"`
	Branch string `json:"branch,omitempty"`
	Committer *Identity `json:"committer,omitempty"`
	Dates *CommitDateOptions `json:"dates,omitempty"`
	Files []*ChangeFileOperation `json:"files,omitempty"`
	ForceOverwriteNewBranch bool `json:"force_overwrite_new_branch,omitempty"`
	Message string `json:"message,omitempty"`
	NewBranch string `json:"new_branch,omitempty"`
	Signoff bool `json:"signoff,omitempty"`
}

type ChangedFile struct {
	Additions int64 `json:"additions,omitempty"`
	Changes int64 `json:"changes,omitempty"`
	ContentsUrl string `json:"contents_url,omitempty"`
	Deletions int64 `json:"deletions,omitempty"`
	Filename string `json:"filename,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	PreviousFilename string `json:"previous_filename,omitempty"`
	RawUrl string `json:"raw_url,omitempty"`
	Status string `json:"status,omitempty"`
}

type CombinedStatus struct {
	CommitUrl string `json:"commit_url,omitempty"`
	Repository *Repository `json:"repository,omitempty"`
	Sha string `json:"sha,omitempty"`
	State *CommitStatusState `json:"state,omitempty"`
	Statuses []*CommitStatus `json:"statuses,omitempty"`
	TotalCount int64 `json:"total_count,omitempty"`
	Url string `json:"url,omitempty"`
}

type Comment struct {
	Assets []*Attachment `json:"assets,omitempty"`
	Body string `json:"body,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	IssueUrl string `json:"issue_url,omitempty"`
	OriginalAuthor string `json:"original_author,omitempty"`
	OriginalAuthorId int64 `json:"original_author_id,omitempty"`
	PullRequestUrl string `json:"pull_request_url,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	User *User `json:"user,omitempty"`
}

type Commit struct {
	Author *User `json:"author,omitempty"`
	Commit *RepoCommit `json:"commit,omitempty"`
	Committer *User `json:"committer,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	Files []*CommitAffectedFiles `json:"files,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Parents []*CommitMeta `json:"parents,omitempty"`
	Sha string `json:"sha,omitempty"`
	Stats *CommitStats `json:"stats,omitempty"`
	Url string `json:"url,omitempty"`
}

type CommitAffectedFiles struct {
	Filename string `json:"filename,omitempty"`
	Status string `json:"status,omitempty"`
}

type CommitDateOptions struct {
	Author *time.Time `json:"author,omitempty"`
	Committer *time.Time `json:"committer,omitempty"`
}

type CommitMeta struct {
	Created *time.Time `json:"created,omitempty"`
	Sha string `json:"sha,omitempty"`
	Url string `json:"url,omitempty"`
}

type CommitStats struct {
	Additions int64 `json:"additions,omitempty"`
	Deletions int64 `json:"deletions,omitempty"`
	Total int64 `json:"total,omitempty"`
}

type CommitStatus struct {
	Context string `json:"context,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Creator *User `json:"creator,omitempty"`
	Description string `json:"description,omitempty"`
	Id int64 `json:"id,omitempty"`
	Status *CommitStatusState `json:"status,omitempty"`
	TargetUrl string `json:"target_url,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
}

type CommitStatusState string

type CommitUser struct {
	Date string `json:"date,omitempty"`
	Email string `json:"email,omitempty"`
	Name string `json:"name,omitempty"`
}

type Compare struct {
	Commits []*Commit `json:"commits,omitempty"`
	Files []*CommitAffectedFiles `json:"files,omitempty"`
	TotalCommits int64 `json:"total_commits,omitempty"`
}

type ContentsResponse struct {
	XLinks *FileLinksResponse `json:"_links,omitempty"`
	Content string `json:"content,omitempty"`
	DownloadUrl string `json:"download_url,omitempty"`
	Encoding string `json:"encoding,omitempty"`
	GitUrl string `json:"git_url,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	LastCommitSha string `json:"last_commit_sha,omitempty"`
	LastCommitWhen *time.Time `json:"last_commit_when,omitempty"`
	Name string `json:"name,omitempty"`
	Path string `json:"path,omitempty"`
	Sha string `json:"sha,omitempty"`
	Size int64 `json:"size,omitempty"`
	SubmoduleGitUrl string `json:"submodule_git_url,omitempty"`
	Target string `json:"target,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
}

type CreateAccessTokenOption struct {
	Name string `json:"name,omitempty"`
	Repositories []*RepoTargetOption `json:"repositories,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
}

type CreateBranchProtectionOption struct {
	ApplyToAdmins bool `json:"apply_to_admins,omitempty"`
	ApprovalsWhitelistTeams []string `json:"approvals_whitelist_teams,omitempty"`
	ApprovalsWhitelistUsername []string `json:"approvals_whitelist_username,omitempty"`
	BlockOnOfficialReviewRequests bool `json:"block_on_official_review_requests,omitempty"`
	BlockOnOutdatedBranch bool `json:"block_on_outdated_branch,omitempty"`
	BlockOnRejectedReviews bool `json:"block_on_rejected_reviews,omitempty"`
	BranchName string `json:"branch_name,omitempty"`
	DismissStaleApprovals bool `json:"dismiss_stale_approvals,omitempty"`
	EnableApprovalsWhitelist bool `json:"enable_approvals_whitelist,omitempty"`
	EnableMergeWhitelist bool `json:"enable_merge_whitelist,omitempty"`
	EnablePush bool `json:"enable_push,omitempty"`
	EnablePushWhitelist bool `json:"enable_push_whitelist,omitempty"`
	EnableStatusCheck bool `json:"enable_status_check,omitempty"`
	IgnoreStaleApprovals bool `json:"ignore_stale_approvals,omitempty"`
	MergeWhitelistTeams []string `json:"merge_whitelist_teams,omitempty"`
	MergeWhitelistUsernames []string `json:"merge_whitelist_usernames,omitempty"`
	ProtectedFilePatterns string `json:"protected_file_patterns,omitempty"`
	PushWhitelistDeployKeys bool `json:"push_whitelist_deploy_keys,omitempty"`
	PushWhitelistTeams []string `json:"push_whitelist_teams,omitempty"`
	PushWhitelistUsernames []string `json:"push_whitelist_usernames,omitempty"`
	RequireSignedCommits bool `json:"require_signed_commits,omitempty"`
	RequiredApprovals int64 `json:"required_approvals,omitempty"`
	RuleName string `json:"rule_name,omitempty"`
	StatusCheckContexts []string `json:"status_check_contexts,omitempty"`
	UnprotectedFilePatterns string `json:"unprotected_file_patterns,omitempty"`
}

type CreateBranchRepoOption struct {
	NewBranchName string `json:"new_branch_name,omitempty"`
	OldBranchName string `json:"old_branch_name,omitempty"`
	OldRefName string `json:"old_ref_name,omitempty"`
}

type CreateEmailOption struct {
	Emails []string `json:"emails,omitempty"`
}

type CreateFileOptions struct {
	Author *Identity `json:"author,omitempty"`
	Branch string `json:"branch,omitempty"`
	Committer *Identity `json:"committer,omitempty"`
	Content string `json:"content,omitempty"`
	Dates *CommitDateOptions `json:"dates,omitempty"`
	ForceOverwriteNewBranch bool `json:"force_overwrite_new_branch,omitempty"`
	Message string `json:"message,omitempty"`
	NewBranch string `json:"new_branch,omitempty"`
	Signoff bool `json:"signoff,omitempty"`
}

type CreateForkOption struct {
	Name string `json:"name,omitempty"`
	Organization string `json:"organization,omitempty"`
}

type CreateGPGKeyOption struct {
	ArmoredPublicKey string `json:"armored_public_key,omitempty"`
	ArmoredSignature string `json:"armored_signature,omitempty"`
}

type CreateHookOption struct {
	Active bool `json:"active,omitempty"`
	AuthorizationHeader string `json:"authorization_header,omitempty"`
	BranchFilter string `json:"branch_filter,omitempty"`
	Config *CreateHookOptionConfig `json:"config,omitempty"`
	Events []string `json:"events,omitempty"`
	Type_ string `json:"type,omitempty"`
}

type CreateHookOptionConfig interface{}

type CreateIssueCommentOption struct {
	Body string `json:"body,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type CreateIssueOption struct {
	Assignee string `json:"assignee,omitempty"`
	Assignees []string `json:"assignees,omitempty"`
	Body string `json:"body,omitempty"`
	Closed bool `json:"closed,omitempty"`
	DueDate *time.Time `json:"due_date,omitempty"`
	Labels []int64 `json:"labels,omitempty"`
	Milestone int64 `json:"milestone,omitempty"`
	Ref string `json:"ref,omitempty"`
	Title string `json:"title,omitempty"`
}

type CreateKeyOption struct {
	Key string `json:"key,omitempty"`
	ReadOnly bool `json:"read_only,omitempty"`
	Title string `json:"title,omitempty"`
}

type CreateLabelOption struct {
	Color string `json:"color,omitempty"`
	Description string `json:"description,omitempty"`
	Exclusive bool `json:"exclusive,omitempty"`
	IsArchived bool `json:"is_archived,omitempty"`
	Name string `json:"name,omitempty"`
}

type CreateMilestoneOption struct {
	Description string `json:"description,omitempty"`
	DueOn *time.Time `json:"due_on,omitempty"`
	State string `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
}

type CreateOAuth2ApplicationOptions struct {
	ConfidentialClient bool `json:"confidential_client,omitempty"`
	Name string `json:"name,omitempty"`
	RedirectUris []string `json:"redirect_uris,omitempty"`
}

type CreateOrUpdateSecretOption struct {
	Data string `json:"data,omitempty"`
}

type CreateOrgOption struct {
	Description string `json:"description,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	Location string `json:"location,omitempty"`
	RepoAdminChangeTeamAccess bool `json:"repo_admin_change_team_access,omitempty"`
	Username string `json:"username,omitempty"`
	Visibility string `json:"visibility,omitempty"`
	Website string `json:"website,omitempty"`
}

type CreatePullRequestOption struct {
	Assignee string `json:"assignee,omitempty"`
	Assignees []string `json:"assignees,omitempty"`
	Base string `json:"base,omitempty"`
	Body string `json:"body,omitempty"`
	DueDate *time.Time `json:"due_date,omitempty"`
	Head string `json:"head,omitempty"`
	Labels []int64 `json:"labels,omitempty"`
	Milestone int64 `json:"milestone,omitempty"`
	Title string `json:"title,omitempty"`
}

type CreatePullReviewComment struct {
	Body string `json:"body,omitempty"`
	ExtraLinesCount int64 `json:"extra_lines_count,omitempty"`
	NewPosition int64 `json:"new_position,omitempty"`
	OldPosition int64 `json:"old_position,omitempty"`
	Path string `json:"path,omitempty"`
}

type CreatePullReviewCommentOptions map[string]interface{}

type CreatePullReviewOptions struct {
	Body string `json:"body,omitempty"`
	Comments []*CreatePullReviewComment `json:"comments,omitempty"`
	CommitId string `json:"commit_id,omitempty"`
	Event *ReviewStateType `json:"event,omitempty"`
}

type CreatePushMirrorOption struct {
	BranchFilter string `json:"branch_filter,omitempty"`
	Interval string `json:"interval,omitempty"`
	RemoteAddress string `json:"remote_address,omitempty"`
	RemotePassword string `json:"remote_password,omitempty"`
	RemoteUsername string `json:"remote_username,omitempty"`
	SyncOnCommit bool `json:"sync_on_commit,omitempty"`
	UseSsh bool `json:"use_ssh,omitempty"`
}

type CreateQuotaGroupOptions struct {
	Name string `json:"name,omitempty"`
	Rules []*CreateQuotaRuleOptions `json:"rules,omitempty"`
}

type CreateQuotaRuleOptions struct {
	Limit int64 `json:"limit,omitempty"`
	Name string `json:"name,omitempty"`
	Subjects []string `json:"subjects,omitempty"`
}

type CreateReleaseOption struct {
	Body string `json:"body,omitempty"`
	Draft bool `json:"draft,omitempty"`
	HideArchiveLinks bool `json:"hide_archive_links,omitempty"`
	Name string `json:"name,omitempty"`
	Prerelease bool `json:"prerelease,omitempty"`
	TagName string `json:"tag_name,omitempty"`
	TargetCommitish string `json:"target_commitish,omitempty"`
}

type CreateRepoOption struct {
	AutoInit bool `json:"auto_init,omitempty"`
	DefaultBranch string `json:"default_branch,omitempty"`
	Description string `json:"description,omitempty"`
	Gitignores string `json:"gitignores,omitempty"`
	IssueLabels string `json:"issue_labels,omitempty"`
	License string `json:"license,omitempty"`
	Name string `json:"name,omitempty"`
	ObjectFormatName string `json:"object_format_name,omitempty"`
	Private bool `json:"private,omitempty"`
	Readme string `json:"readme,omitempty"`
	Template bool `json:"template,omitempty"`
	TrustModel string `json:"trust_model,omitempty"`
}

type CreateStatusOption struct {
	Context string `json:"context,omitempty"`
	Description string `json:"description,omitempty"`
	State *CommitStatusState `json:"state,omitempty"`
	TargetUrl string `json:"target_url,omitempty"`
}

type CreateTagOption struct {
	Message string `json:"message,omitempty"`
	TagName string `json:"tag_name,omitempty"`
	Target string `json:"target,omitempty"`
}

type CreateTagProtectionOption struct {
	NamePattern string `json:"name_pattern,omitempty"`
	WhitelistTeams []string `json:"whitelist_teams,omitempty"`
	WhitelistUsernames []string `json:"whitelist_usernames,omitempty"`
}

type CreateTeamOption struct {
	CanCreateOrgRepo bool `json:"can_create_org_repo,omitempty"`
	Description string `json:"description,omitempty"`
	IncludesAllRepositories bool `json:"includes_all_repositories,omitempty"`
	Name string `json:"name,omitempty"`
	Permission string `json:"permission,omitempty"`
	Units []string `json:"units,omitempty"`
	UnitsMap map[string]string `json:"units_map,omitempty"`
}

type CreateUserOption struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	LoginName string `json:"login_name,omitempty"`
	MustChangePassword bool `json:"must_change_password,omitempty"`
	Password string `json:"password,omitempty"`
	Restricted bool `json:"restricted,omitempty"`
	SendNotify bool `json:"send_notify,omitempty"`
	SourceId int64 `json:"source_id,omitempty"`
	Username string `json:"username,omitempty"`
	Visibility string `json:"visibility,omitempty"`
}

type CreateVariableOption struct {
	Value string `json:"value,omitempty"`
}

type CreateWikiPageOptions struct {
	ContentBase64 string `json:"content_base64,omitempty"`
	Message string `json:"message,omitempty"`
	Title string `json:"title,omitempty"`
}

type Cron struct {
	ExecTimes int64 `json:"exec_times,omitempty"`
	Name string `json:"name,omitempty"`
	Next *time.Time `json:"next,omitempty"`
	Prev *time.Time `json:"prev,omitempty"`
	Schedule string `json:"schedule,omitempty"`
}

type DeleteEmailOption struct {
	Emails []string `json:"emails,omitempty"`
}

type DeleteFileOptions struct {
	Author *Identity `json:"author,omitempty"`
	Branch string `json:"branch,omitempty"`
	Committer *Identity `json:"committer,omitempty"`
	Dates *CommitDateOptions `json:"dates,omitempty"`
	ForceOverwriteNewBranch bool `json:"force_overwrite_new_branch,omitempty"`
	Message string `json:"message,omitempty"`
	NewBranch string `json:"new_branch,omitempty"`
	Sha string `json:"sha,omitempty"`
	Signoff bool `json:"signoff,omitempty"`
}

type DeleteLabelsOption struct {
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type DeployKey struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Fingerprint string `json:"fingerprint,omitempty"`
	Id int64 `json:"id,omitempty"`
	Key string `json:"key,omitempty"`
	KeyId int64 `json:"key_id,omitempty"`
	ReadOnly bool `json:"read_only,omitempty"`
	Repository *Repository `json:"repository,omitempty"`
	Title string `json:"title,omitempty"`
	Url string `json:"url,omitempty"`
}

type DismissPullReviewOptions struct {
	Message string `json:"message,omitempty"`
	Priors bool `json:"priors,omitempty"`
}

type DispatchWorkflowOption struct {
	Inputs map[string]string `json:"inputs,omitempty"`
	Ref string `json:"ref,omitempty"`
	ReturnRunInfo bool `json:"return_run_info,omitempty"`
}

type DispatchWorkflowRun struct {
	Id int64 `json:"id,omitempty"`
	Jobs []string `json:"jobs,omitempty"`
	RunNumber int64 `json:"run_number,omitempty"`
}

type Duration time.Duration

type EditAttachmentOptions struct {
	BrowserDownloadUrl string `json:"browser_download_url,omitempty"`
	Name string `json:"name,omitempty"`
}

type EditBranchProtectionOption struct {
	ApplyToAdmins bool `json:"apply_to_admins,omitempty"`
	ApprovalsWhitelistTeams []string `json:"approvals_whitelist_teams,omitempty"`
	ApprovalsWhitelistUsername []string `json:"approvals_whitelist_username,omitempty"`
	BlockOnOfficialReviewRequests bool `json:"block_on_official_review_requests,omitempty"`
	BlockOnOutdatedBranch bool `json:"block_on_outdated_branch,omitempty"`
	BlockOnRejectedReviews bool `json:"block_on_rejected_reviews,omitempty"`
	DismissStaleApprovals bool `json:"dismiss_stale_approvals,omitempty"`
	EnableApprovalsWhitelist bool `json:"enable_approvals_whitelist,omitempty"`
	EnableMergeWhitelist bool `json:"enable_merge_whitelist,omitempty"`
	EnablePush bool `json:"enable_push,omitempty"`
	EnablePushWhitelist bool `json:"enable_push_whitelist,omitempty"`
	EnableStatusCheck bool `json:"enable_status_check,omitempty"`
	IgnoreStaleApprovals bool `json:"ignore_stale_approvals,omitempty"`
	MergeWhitelistTeams []string `json:"merge_whitelist_teams,omitempty"`
	MergeWhitelistUsernames []string `json:"merge_whitelist_usernames,omitempty"`
	ProtectedFilePatterns string `json:"protected_file_patterns,omitempty"`
	PushWhitelistDeployKeys bool `json:"push_whitelist_deploy_keys,omitempty"`
	PushWhitelistTeams []string `json:"push_whitelist_teams,omitempty"`
	PushWhitelistUsernames []string `json:"push_whitelist_usernames,omitempty"`
	RequireSignedCommits bool `json:"require_signed_commits,omitempty"`
	RequiredApprovals int64 `json:"required_approvals,omitempty"`
	StatusCheckContexts []string `json:"status_check_contexts,omitempty"`
	UnprotectedFilePatterns string `json:"unprotected_file_patterns,omitempty"`
}

type EditDeadlineOption struct {
	DueDate time.Time `json:"due_date,omitempty"`
}

type EditGitHookOption struct {
	Content string `json:"content,omitempty"`
}

type EditHookOption struct {
	Active bool `json:"active,omitempty"`
	AuthorizationHeader string `json:"authorization_header,omitempty"`
	BranchFilter string `json:"branch_filter,omitempty"`
	Config map[string]string `json:"config,omitempty"`
	Events []string `json:"events,omitempty"`
}

type EditIssueCommentOption struct {
	Body string `json:"body,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type EditIssueOption struct {
	Assignee string `json:"assignee,omitempty"`
	Assignees []string `json:"assignees,omitempty"`
	Body string `json:"body,omitempty"`
	DueDate *time.Time `json:"due_date,omitempty"`
	Milestone int64 `json:"milestone,omitempty"`
	Ref string `json:"ref,omitempty"`
	State string `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
	UnsetDueDate bool `json:"unset_due_date,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type EditLabelOption struct {
	Color string `json:"color,omitempty"`
	Description string `json:"description,omitempty"`
	Exclusive bool `json:"exclusive,omitempty"`
	IsArchived bool `json:"is_archived,omitempty"`
	Name string `json:"name,omitempty"`
}

type EditMilestoneOption struct {
	Description string `json:"description,omitempty"`
	DueOn *time.Time `json:"due_on,omitempty"`
	State string `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
}

type EditOrgOption struct {
	Description string `json:"description,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	Location string `json:"location,omitempty"`
	RepoAdminChangeTeamAccess bool `json:"repo_admin_change_team_access,omitempty"`
	Visibility string `json:"visibility,omitempty"`
	Website string `json:"website,omitempty"`
}

type EditPullRequestOption struct {
	AllowMaintainerEdit bool `json:"allow_maintainer_edit,omitempty"`
	Assignee string `json:"assignee,omitempty"`
	Assignees []string `json:"assignees,omitempty"`
	Base string `json:"base,omitempty"`
	Body string `json:"body,omitempty"`
	DueDate *time.Time `json:"due_date,omitempty"`
	Labels []int64 `json:"labels,omitempty"`
	Milestone int64 `json:"milestone,omitempty"`
	State string `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
	UnsetDueDate bool `json:"unset_due_date,omitempty"`
}

type EditQuotaRuleOptions struct {
	Limit int64 `json:"limit,omitempty"`
	Subjects []string `json:"subjects,omitempty"`
}

type EditReactionOption struct {
	Content string `json:"content,omitempty"`
}

type EditReleaseOption struct {
	Body string `json:"body,omitempty"`
	Draft bool `json:"draft,omitempty"`
	HideArchiveLinks bool `json:"hide_archive_links,omitempty"`
	Name string `json:"name,omitempty"`
	Prerelease bool `json:"prerelease,omitempty"`
	TagName string `json:"tag_name,omitempty"`
	TargetCommitish string `json:"target_commitish,omitempty"`
}

type EditRepoOption struct {
	AllowFastForwardOnlyMerge bool `json:"allow_fast_forward_only_merge,omitempty"`
	AllowManualMerge bool `json:"allow_manual_merge,omitempty"`
	AllowMergeCommits bool `json:"allow_merge_commits,omitempty"`
	AllowRebase bool `json:"allow_rebase,omitempty"`
	AllowRebaseExplicit bool `json:"allow_rebase_explicit,omitempty"`
	AllowRebaseUpdate bool `json:"allow_rebase_update,omitempty"`
	AllowSquashMerge bool `json:"allow_squash_merge,omitempty"`
	Archived bool `json:"archived,omitempty"`
	AutodetectManualMerge bool `json:"autodetect_manual_merge,omitempty"`
	DefaultAllowMaintainerEdit bool `json:"default_allow_maintainer_edit,omitempty"`
	DefaultBranch string `json:"default_branch,omitempty"`
	DefaultDeleteBranchAfterMerge bool `json:"default_delete_branch_after_merge,omitempty"`
	DefaultMergeStyle string `json:"default_merge_style,omitempty"`
	DefaultUpdateStyle string `json:"default_update_style,omitempty"`
	Description string `json:"description,omitempty"`
	EnablePrune bool `json:"enable_prune,omitempty"`
	ExternalTracker *ExternalTracker `json:"external_tracker,omitempty"`
	ExternalWiki *ExternalWiki `json:"external_wiki,omitempty"`
	GloballyEditableWiki bool `json:"globally_editable_wiki,omitempty"`
	HasActions bool `json:"has_actions,omitempty"`
	HasIssues bool `json:"has_issues,omitempty"`
	HasPackages bool `json:"has_packages,omitempty"`
	HasProjects bool `json:"has_projects,omitempty"`
	HasPullRequests bool `json:"has_pull_requests,omitempty"`
	HasReleases bool `json:"has_releases,omitempty"`
	HasWiki bool `json:"has_wiki,omitempty"`
	IgnoreWhitespaceConflicts bool `json:"ignore_whitespace_conflicts,omitempty"`
	InternalTracker *InternalTracker `json:"internal_tracker,omitempty"`
	MirrorInterval string `json:"mirror_interval,omitempty"`
	Name string `json:"name,omitempty"`
	Private bool `json:"private,omitempty"`
	Template bool `json:"template,omitempty"`
	Website string `json:"website,omitempty"`
	WikiBranch string `json:"wiki_branch,omitempty"`
}

type EditTagProtectionOption struct {
	NamePattern string `json:"name_pattern,omitempty"`
	WhitelistTeams []string `json:"whitelist_teams,omitempty"`
	WhitelistUsernames []string `json:"whitelist_usernames,omitempty"`
}

type EditTeamOption struct {
	CanCreateOrgRepo bool `json:"can_create_org_repo,omitempty"`
	Description string `json:"description,omitempty"`
	IncludesAllRepositories bool `json:"includes_all_repositories,omitempty"`
	Name string `json:"name,omitempty"`
	Permission string `json:"permission,omitempty"`
	Units []string `json:"units,omitempty"`
	UnitsMap map[string]string `json:"units_map,omitempty"`
}

type EditUserOption struct {
	Active bool `json:"active,omitempty"`
	Admin bool `json:"admin,omitempty"`
	AllowCreateOrganization bool `json:"allow_create_organization,omitempty"`
	AllowGitHook bool `json:"allow_git_hook,omitempty"`
	AllowImportLocal bool `json:"allow_import_local,omitempty"`
	Description string `json:"description,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	HideEmail bool `json:"hide_email,omitempty"`
	Location string `json:"location,omitempty"`
	LoginName string `json:"login_name,omitempty"`
	MaxRepoCreation int64 `json:"max_repo_creation,omitempty"`
	MustChangePassword bool `json:"must_change_password,omitempty"`
	Password string `json:"password,omitempty"`
	ProhibitLogin bool `json:"prohibit_login,omitempty"`
	Pronouns string `json:"pronouns,omitempty"`
	Restricted bool `json:"restricted,omitempty"`
	SourceId int64 `json:"source_id,omitempty"`
	Visibility string `json:"visibility,omitempty"`
	Website string `json:"website,omitempty"`
}

type Email struct {
	Email string `json:"email,omitempty"`
	Primary bool `json:"primary,omitempty"`
	UserId int64 `json:"user_id,omitempty"`
	Username string `json:"username,omitempty"`
	Verified bool `json:"verified,omitempty"`
}

type ExternalTracker struct {
	ExternalTrackerFormat string `json:"external_tracker_format,omitempty"`
	ExternalTrackerRegexpPattern string `json:"external_tracker_regexp_pattern,omitempty"`
	ExternalTrackerStyle string `json:"external_tracker_style,omitempty"`
	ExternalTrackerUrl string `json:"external_tracker_url,omitempty"`
}

type ExternalWiki struct {
	ExternalWikiUrl string `json:"external_wiki_url,omitempty"`
}

type FileCommitResponse struct {
	Author *CommitUser `json:"author,omitempty"`
	Committer *CommitUser `json:"committer,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Message string `json:"message,omitempty"`
	Parents []*CommitMeta `json:"parents,omitempty"`
	Sha string `json:"sha,omitempty"`
	Tree *CommitMeta `json:"tree,omitempty"`
	Url string `json:"url,omitempty"`
}

type FileDeleteResponse struct {
	Commit *FileCommitResponse `json:"commit,omitempty"`
	Content interface{} `json:"content,omitempty"`
	Verification *PayloadCommitVerification `json:"verification,omitempty"`
}

type FileLinksResponse struct {
	Git string `json:"git,omitempty"`
	Html string `json:"html,omitempty"`
	Self string `json:"self,omitempty"`
}

type FileResponse struct {
	Commit *FileCommitResponse `json:"commit,omitempty"`
	Content *ContentsResponse `json:"content,omitempty"`
	Verification *PayloadCommitVerification `json:"verification,omitempty"`
}

type FilesResponse struct {
	Commit *FileCommitResponse `json:"commit,omitempty"`
	Files []*ContentsResponse `json:"files,omitempty"`
	Verification *PayloadCommitVerification `json:"verification,omitempty"`
}

type ForgeLike struct {
}

type ForgeOutbox struct {
}

type GPGKey struct {
	CanCertify bool `json:"can_certify,omitempty"`
	CanEncryptComms bool `json:"can_encrypt_comms,omitempty"`
	CanEncryptStorage bool `json:"can_encrypt_storage,omitempty"`
	CanSign bool `json:"can_sign,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Emails []*GPGKeyEmail `json:"emails,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Id int64 `json:"id,omitempty"`
	KeyId string `json:"key_id,omitempty"`
	PrimaryKeyId string `json:"primary_key_id,omitempty"`
	PublicKey string `json:"public_key,omitempty"`
	Subkeys []*GPGKey `json:"subkeys,omitempty"`
	Verified bool `json:"verified,omitempty"`
}

type GPGKeyEmail struct {
	Email string `json:"email,omitempty"`
	Verified bool `json:"verified,omitempty"`
}

type GeneralAPISettings struct {
	DefaultGitTreesPerPage int64 `json:"default_git_trees_per_page,omitempty"`
	DefaultMaxBlobSize int64 `json:"default_max_blob_size,omitempty"`
	DefaultPagingNum int64 `json:"default_paging_num,omitempty"`
	MaxResponseItems int64 `json:"max_response_items,omitempty"`
}

type GeneralAttachmentSettings struct {
	AllowedTypes string `json:"allowed_types,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	MaxFiles int64 `json:"max_files,omitempty"`
	MaxSize int64 `json:"max_size,omitempty"`
}

type GeneralRepoSettings struct {
	ForksDisabled bool `json:"forks_disabled,omitempty"`
	HttpGitDisabled bool `json:"http_git_disabled,omitempty"`
	LfsDisabled bool `json:"lfs_disabled,omitempty"`
	MigrationsDisabled bool `json:"migrations_disabled,omitempty"`
	MirrorsDisabled bool `json:"mirrors_disabled,omitempty"`
	StarsDisabled bool `json:"stars_disabled,omitempty"`
	TimeTrackingDisabled bool `json:"time_tracking_disabled,omitempty"`
}

type GeneralUISettings struct {
	AllowedReactions []string `json:"allowed_reactions,omitempty"`
	CustomEmojis []string `json:"custom_emojis,omitempty"`
	DefaultTheme string `json:"default_theme,omitempty"`
}

type GenerateRepoOption struct {
	Avatar bool `json:"avatar,omitempty"`
	DefaultBranch string `json:"default_branch,omitempty"`
	Description string `json:"description,omitempty"`
	GitContent bool `json:"git_content,omitempty"`
	GitHooks bool `json:"git_hooks,omitempty"`
	Labels bool `json:"labels,omitempty"`
	Name string `json:"name,omitempty"`
	Owner string `json:"owner,omitempty"`
	Private bool `json:"private,omitempty"`
	ProtectedBranch bool `json:"protected_branch,omitempty"`
	Topics bool `json:"topics,omitempty"`
	Webhooks bool `json:"webhooks,omitempty"`
}

type GitBlob struct {
	Content string `json:"content,omitempty"`
	Encoding string `json:"encoding,omitempty"`
	Sha string `json:"sha,omitempty"`
	Size int64 `json:"size,omitempty"`
	Url string `json:"url,omitempty"`
}

type GitEntry struct {
	Mode string `json:"mode,omitempty"`
	Path string `json:"path,omitempty"`
	Sha string `json:"sha,omitempty"`
	Size int64 `json:"size,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
}

type GitHook struct {
	Content string `json:"content,omitempty"`
	IsActive bool `json:"is_active,omitempty"`
	Name string `json:"name,omitempty"`
}

type GitObject struct {
	Sha string `json:"sha,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
}

type GitTreeResponse struct {
	Page int64 `json:"page,omitempty"`
	Sha string `json:"sha,omitempty"`
	TotalCount int64 `json:"total_count,omitempty"`
	Tree []*GitEntry `json:"tree,omitempty"`
	Truncated bool `json:"truncated,omitempty"`
	Url string `json:"url,omitempty"`
}

type GitignoreTemplateInfo struct {
	Name string `json:"name,omitempty"`
	Source string `json:"source,omitempty"`
}

type Hook struct {
	Active bool `json:"active,omitempty"`
	AuthorizationHeader string `json:"authorization_header,omitempty"`
	BranchFilter string `json:"branch_filter,omitempty"`
	Config map[string]string `json:"config,omitempty"`
	ContentType string `json:"content_type,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Events []string `json:"events,omitempty"`
	Id int64 `json:"id,omitempty"`
	Metadata interface{} `json:"metadata,omitempty"`
	Type_ string `json:"type,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
}

type Identity struct {
	Email string `json:"email,omitempty"`
	Name string `json:"name,omitempty"`
}

type InternalTracker struct {
	AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time,omitempty"`
	EnableIssueDependencies bool `json:"enable_issue_dependencies,omitempty"`
	EnableTimeTracker bool `json:"enable_time_tracker,omitempty"`
}

type Issue struct {
	Assets []*Attachment `json:"assets,omitempty"`
	Assignee *User `json:"assignee,omitempty"`
	Assignees []*User `json:"assignees,omitempty"`
	Body string `json:"body,omitempty"`
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	Comments int64 `json:"comments,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DueDate *time.Time `json:"due_date,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	IsLocked bool `json:"is_locked,omitempty"`
	Labels []*Label `json:"labels,omitempty"`
	Milestone *Milestone `json:"milestone,omitempty"`
	Number int64 `json:"number,omitempty"`
	OriginalAuthor string `json:"original_author,omitempty"`
	OriginalAuthorId int64 `json:"original_author_id,omitempty"`
	PinOrder int64 `json:"pin_order,omitempty"`
	PullRequest *PullRequestMeta `json:"pull_request,omitempty"`
	Ref string `json:"ref,omitempty"`
	Repository *RepositoryMeta `json:"repository,omitempty"`
	State *StateType `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
	User *User `json:"user,omitempty"`
}

type IssueConfig struct {
	BlankIssuesEnabled bool `json:"blank_issues_enabled,omitempty"`
	ContactLinks []*IssueConfigContactLink `json:"contact_links,omitempty"`
}

type IssueConfigContactLink struct {
	About string `json:"about,omitempty"`
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
}

type IssueConfigValidation struct {
	Message string `json:"message,omitempty"`
	Valid bool `json:"valid,omitempty"`
}

type IssueDeadline struct {
	DueDate *time.Time `json:"due_date,omitempty"`
}

type IssueFormField struct {
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Id string `json:"id,omitempty"`
	Type_ *IssueFormFieldType `json:"type,omitempty"`
	Validations map[string]interface{} `json:"validations,omitempty"`
	Visible []*IssueFormFieldVisible `json:"visible,omitempty"`
}

type IssueFormFieldType string

type IssueFormFieldVisible string

type IssueLabelsOption struct {
	Labels []interface{} `json:"labels,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type IssueMeta struct {
	Index int64 `json:"index,omitempty"`
	Owner string `json:"owner,omitempty"`
	Repo string `json:"repo,omitempty"`
}

type IssueTemplate struct {
	About string `json:"about,omitempty"`
	Body []*IssueFormField `json:"body,omitempty"`
	Content string `json:"content,omitempty"`
	FileName string `json:"file_name,omitempty"`
	Labels *IssueTemplateLabels `json:"labels,omitempty"`
	Name string `json:"name,omitempty"`
	Ref string `json:"ref,omitempty"`
	Title string `json:"title,omitempty"`
}

type IssueTemplateLabels []string

type Label struct {
	Color string `json:"color,omitempty"`
	Description string `json:"description,omitempty"`
	Exclusive bool `json:"exclusive,omitempty"`
	Id int64 `json:"id,omitempty"`
	IsArchived bool `json:"is_archived,omitempty"`
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
}

type LabelTemplate struct {
	Color string `json:"color,omitempty"`
	Description string `json:"description,omitempty"`
	Exclusive bool `json:"exclusive,omitempty"`
	Name string `json:"name,omitempty"`
}

type LicenseTemplateInfo struct {
	Body string `json:"body,omitempty"`
	Implementation string `json:"implementation,omitempty"`
	Key string `json:"key,omitempty"`
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
}

type LicensesTemplateListEntry struct {
	Key string `json:"key,omitempty"`
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
}

type ListActionRunResponse struct {
	TotalCount int64 `json:"total_count,omitempty"`
	WorkflowRuns []*ActionRun `json:"workflow_runs,omitempty"`
}

type MarkdownOption struct {
	Context string `json:"Context,omitempty"`
	Mode string `json:"Mode,omitempty"`
	Text string `json:"Text,omitempty"`
	Wiki bool `json:"Wiki,omitempty"`
}

type MarkupOption struct {
	BranchPath string `json:"BranchPath,omitempty"`
	Context string `json:"Context,omitempty"`
	FilePath string `json:"FilePath,omitempty"`
	Mode string `json:"Mode,omitempty"`
	Text string `json:"Text,omitempty"`
	Wiki bool `json:"Wiki,omitempty"`
}

type MergePullRequestOption struct {
	Do string `json:"Do,omitempty"`
	MergeCommitID string `json:"MergeCommitID,omitempty"`
	MergeMessageField string `json:"MergeMessageField,omitempty"`
	MergeTitleField string `json:"MergeTitleField,omitempty"`
	DeleteBranchAfterMerge bool `json:"delete_branch_after_merge,omitempty"`
	ForceMerge bool `json:"force_merge,omitempty"`
	HeadCommitId string `json:"head_commit_id,omitempty"`
	MergeWhenChecksSucceed bool `json:"merge_when_checks_succeed,omitempty"`
}

type MigrateRepoOptions struct {
	AuthPassword string `json:"auth_password,omitempty"`
	AuthToken string `json:"auth_token,omitempty"`
	AuthUsername string `json:"auth_username,omitempty"`
	CloneAddr string `json:"clone_addr,omitempty"`
	Description string `json:"description,omitempty"`
	Issues bool `json:"issues,omitempty"`
	Labels bool `json:"labels,omitempty"`
	Lfs bool `json:"lfs,omitempty"`
	LfsEndpoint string `json:"lfs_endpoint,omitempty"`
	Milestones bool `json:"milestones,omitempty"`
	Mirror bool `json:"mirror,omitempty"`
	MirrorInterval string `json:"mirror_interval,omitempty"`
	Private bool `json:"private,omitempty"`
	PullRequests bool `json:"pull_requests,omitempty"`
	Releases bool `json:"releases,omitempty"`
	RepoName string `json:"repo_name,omitempty"`
	RepoOwner string `json:"repo_owner,omitempty"`
	Service string `json:"service,omitempty"`
	Uid int64 `json:"uid,omitempty"`
	Wiki bool `json:"wiki,omitempty"`
}

type Milestone struct {
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	ClosedIssues int64 `json:"closed_issues,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Description string `json:"description,omitempty"`
	DueOn *time.Time `json:"due_on,omitempty"`
	Id int64 `json:"id,omitempty"`
	OpenIssues int64 `json:"open_issues,omitempty"`
	State *StateType `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type NewIssuePinsAllowed struct {
	Issues bool `json:"issues,omitempty"`
	PullRequests bool `json:"pull_requests,omitempty"`
}

type NodeInfo struct {
	Metadata interface{} `json:"metadata,omitempty"`
	OpenRegistrations bool `json:"openRegistrations,omitempty"`
	Protocols []string `json:"protocols,omitempty"`
	Services *NodeInfoServices `json:"services,omitempty"`
	Software *NodeInfoSoftware `json:"software,omitempty"`
	Usage *NodeInfoUsage `json:"usage,omitempty"`
	Version string `json:"version,omitempty"`
}

type NodeInfoServices struct {
	Inbound []string `json:"inbound,omitempty"`
	Outbound []string `json:"outbound,omitempty"`
}

type NodeInfoSoftware struct {
	Homepage string `json:"homepage,omitempty"`
	Name string `json:"name,omitempty"`
	Repository string `json:"repository,omitempty"`
	Version string `json:"version,omitempty"`
}

type NodeInfoUsage struct {
	LocalComments int64 `json:"localComments,omitempty"`
	LocalPosts int64 `json:"localPosts,omitempty"`
	Users *NodeInfoUsageUsers `json:"users,omitempty"`
}

type NodeInfoUsageUsers struct {
	ActiveHalfyear int64 `json:"activeHalfyear,omitempty"`
	ActiveMonth int64 `json:"activeMonth,omitempty"`
	Total int64 `json:"total,omitempty"`
}

type Note struct {
	Commit *Commit `json:"commit,omitempty"`
	Message string `json:"message,omitempty"`
}

type NoteOptions struct {
	Message string `json:"message,omitempty"`
}

type NotificationCount struct {
	New int64 `json:"new,omitempty"`
}

type NotificationSubject struct {
	HtmlUrl string `json:"html_url,omitempty"`
	LatestCommentHtmlUrl string `json:"latest_comment_html_url,omitempty"`
	LatestCommentUrl string `json:"latest_comment_url,omitempty"`
	State *StateType `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
	Type_ *NotifySubjectType `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
}

type NotificationThread struct {
	Id int64 `json:"id,omitempty"`
	Pinned bool `json:"pinned,omitempty"`
	Repository *Repository `json:"repository,omitempty"`
	Subject *NotificationSubject `json:"subject,omitempty"`
	Unread bool `json:"unread,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
}

type NotifySubjectType string

type OAuth2Application struct {
	ClientId string `json:"client_id,omitempty"`
	ClientSecret string `json:"client_secret,omitempty"`
	ConfidentialClient bool `json:"confidential_client,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	RedirectUris []string `json:"redirect_uris,omitempty"`
}

type Organization struct {
	AvatarUrl string `json:"avatar_url,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	Description string `json:"description,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	Id int64 `json:"id,omitempty"`
	Location string `json:"location,omitempty"`
	Name string `json:"name,omitempty"`
	RepoAdminChangeTeamAccess bool `json:"repo_admin_change_team_access,omitempty"`
	Username string `json:"username,omitempty"`
	Visibility string `json:"visibility,omitempty"`
	Website string `json:"website,omitempty"`
}

type OrganizationPermissions struct {
	CanCreateRepository bool `json:"can_create_repository,omitempty"`
	CanRead bool `json:"can_read,omitempty"`
	CanWrite bool `json:"can_write,omitempty"`
	IsAdmin bool `json:"is_admin,omitempty"`
	IsOwner bool `json:"is_owner,omitempty"`
}

type PRBranchInfo struct {
	Label string `json:"label,omitempty"`
	Ref string `json:"ref,omitempty"`
	Repo *Repository `json:"repo,omitempty"`
	RepoId int64 `json:"repo_id,omitempty"`
	Sha string `json:"sha,omitempty"`
}

type Package struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Creator *User `json:"creator,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Owner *User `json:"owner,omitempty"`
	Repository *Repository `json:"repository,omitempty"`
	Type_ string `json:"type,omitempty"`
	Version string `json:"version,omitempty"`
}

type PackageFile struct {
	Size int64 `json:"Size,omitempty"`
	Id int64 `json:"id,omitempty"`
	Md5 string `json:"md5,omitempty"`
	Name string `json:"name,omitempty"`
	Sha1 string `json:"sha1,omitempty"`
	Sha256 string `json:"sha256,omitempty"`
	Sha512 string `json:"sha512,omitempty"`
}

type PayloadCommit struct {
	Added []string `json:"added,omitempty"`
	Author *PayloadUser `json:"author,omitempty"`
	Committer *PayloadUser `json:"committer,omitempty"`
	Id string `json:"id,omitempty"`
	Message string `json:"message,omitempty"`
	Modified []string `json:"modified,omitempty"`
	Removed []string `json:"removed,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Url string `json:"url,omitempty"`
	Verification *PayloadCommitVerification `json:"verification,omitempty"`
}

type PayloadCommitVerification struct {
	Payload string `json:"payload,omitempty"`
	Reason string `json:"reason,omitempty"`
	Signature string `json:"signature,omitempty"`
	Signer *PayloadUser `json:"signer,omitempty"`
	Verified bool `json:"verified,omitempty"`
}

type PayloadUser struct {
	Email string `json:"email,omitempty"`
	Name string `json:"name,omitempty"`
	Username string `json:"username,omitempty"`
}

type Permission struct {
	Admin bool `json:"admin,omitempty"`
	Pull bool `json:"pull,omitempty"`
	Push bool `json:"push,omitempty"`
}

type PublicKey struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Fingerprint string `json:"fingerprint,omitempty"`
	Id int64 `json:"id,omitempty"`
	Key string `json:"key,omitempty"`
	KeyType string `json:"key_type,omitempty"`
	ReadOnly bool `json:"read_only,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
	User *User `json:"user,omitempty"`
	Verified bool `json:"verified,omitempty"`
}

type PullRequest struct {
	Additions int64 `json:"additions,omitempty"`
	AllowMaintainerEdit bool `json:"allow_maintainer_edit,omitempty"`
	Assignee *User `json:"assignee,omitempty"`
	Assignees []*User `json:"assignees,omitempty"`
	Base *PRBranchInfo `json:"base,omitempty"`
	Body string `json:"body,omitempty"`
	ChangedFiles int64 `json:"changed_files,omitempty"`
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	Comments int64 `json:"comments,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Deletions int64 `json:"deletions,omitempty"`
	DiffUrl string `json:"diff_url,omitempty"`
	Draft bool `json:"draft,omitempty"`
	DueDate *time.Time `json:"due_date,omitempty"`
	Flow int64 `json:"flow,omitempty"`
	Head *PRBranchInfo `json:"head,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	IsLocked bool `json:"is_locked,omitempty"`
	Labels []*Label `json:"labels,omitempty"`
	MergeBase string `json:"merge_base,omitempty"`
	MergeCommitSha string `json:"merge_commit_sha,omitempty"`
	Mergeable bool `json:"mergeable,omitempty"`
	Merged bool `json:"merged,omitempty"`
	MergedAt *time.Time `json:"merged_at,omitempty"`
	MergedBy *User `json:"merged_by,omitempty"`
	Milestone *Milestone `json:"milestone,omitempty"`
	Number int64 `json:"number,omitempty"`
	PatchUrl string `json:"patch_url,omitempty"`
	PinOrder int64 `json:"pin_order,omitempty"`
	RequestedReviewers []*User `json:"requested_reviewers,omitempty"`
	RequestedReviewersTeams []*Team `json:"requested_reviewers_teams,omitempty"`
	ReviewComments int64 `json:"review_comments,omitempty"`
	State *StateType `json:"state,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
	User *User `json:"user,omitempty"`
}

type PullRequestMeta struct {
	Draft bool `json:"draft,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Merged bool `json:"merged,omitempty"`
	MergedAt *time.Time `json:"merged_at,omitempty"`
}

type PullReview struct {
	Body string `json:"body,omitempty"`
	CommentsCount int64 `json:"comments_count,omitempty"`
	CommitId string `json:"commit_id,omitempty"`
	Dismissed bool `json:"dismissed,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	Official bool `json:"official,omitempty"`
	PullRequestUrl string `json:"pull_request_url,omitempty"`
	Stale bool `json:"stale,omitempty"`
	State *ReviewStateType `json:"state,omitempty"`
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	Team *Team `json:"team,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	User *User `json:"user,omitempty"`
}

type PullReviewComment struct {
	Body string `json:"body,omitempty"`
	CommitId string `json:"commit_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DiffHunk string `json:"diff_hunk,omitempty"`
	ExtraLinesCount int64 `json:"extra_lines_count,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	OriginalCommitId string `json:"original_commit_id,omitempty"`
	OriginalPosition int `json:"original_position,omitempty"`
	Path string `json:"path,omitempty"`
	Position int `json:"position,omitempty"`
	PullRequestReviewId int64 `json:"pull_request_review_id,omitempty"`
	PullRequestUrl string `json:"pull_request_url,omitempty"`
	Resolver *User `json:"resolver,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	User *User `json:"user,omitempty"`
}

type PullReviewRequestOptions struct {
	Reviewers []string `json:"reviewers,omitempty"`
	TeamReviewers []string `json:"team_reviewers,omitempty"`
}

type PushMirror struct {
	BranchFilter string `json:"branch_filter,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	Interval string `json:"interval,omitempty"`
	LastError string `json:"last_error,omitempty"`
	LastUpdate *time.Time `json:"last_update,omitempty"`
	PublicKey string `json:"public_key,omitempty"`
	RemoteAddress string `json:"remote_address,omitempty"`
	RemoteName string `json:"remote_name,omitempty"`
	RepoName string `json:"repo_name,omitempty"`
	SyncOnCommit bool `json:"sync_on_commit,omitempty"`
}

type QuotaGroup struct {
	Name string `json:"name,omitempty"`
	Rules []*QuotaRuleInfo `json:"rules,omitempty"`
}

type QuotaGroupList []*QuotaGroup

type QuotaInfo struct {
	Groups *QuotaGroupList `json:"groups,omitempty"`
	Used *QuotaUsed `json:"used,omitempty"`
}

type QuotaRuleInfo struct {
	Limit int64 `json:"limit,omitempty"`
	Name string `json:"name,omitempty"`
	Subjects []string `json:"subjects,omitempty"`
}

type QuotaUsed struct {
	Size *QuotaUsedSize `json:"size,omitempty"`
}

type QuotaUsedArtifact struct {
	HtmlUrl string `json:"html_url,omitempty"`
	Name string `json:"name,omitempty"`
	Size int64 `json:"size,omitempty"`
}

type QuotaUsedArtifactList []*QuotaUsedArtifact

type QuotaUsedAttachment struct {
	ApiUrl string `json:"api_url,omitempty"`
	ContainedIn interface{} `json:"contained_in,omitempty"`
	Name string `json:"name,omitempty"`
	Size int64 `json:"size,omitempty"`
}

type QuotaUsedAttachmentList []*QuotaUsedAttachment

type QuotaUsedPackage struct {
	HtmlUrl string `json:"html_url,omitempty"`
	Name string `json:"name,omitempty"`
	Size int64 `json:"size,omitempty"`
	Type_ string `json:"type,omitempty"`
	Version string `json:"version,omitempty"`
}

type QuotaUsedPackageList []*QuotaUsedPackage

type QuotaUsedSize struct {
	Assets *QuotaUsedSizeAssets `json:"assets,omitempty"`
	Git *QuotaUsedSizeGit `json:"git,omitempty"`
	Repos *QuotaUsedSizeRepos `json:"repos,omitempty"`
}

type QuotaUsedSizeAssets struct {
	Artifacts int64 `json:"artifacts,omitempty"`
	Attachments *QuotaUsedSizeAssetsAttachments `json:"attachments,omitempty"`
	Packages *QuotaUsedSizeAssetsPackages `json:"packages,omitempty"`
}

type QuotaUsedSizeAssetsAttachments struct {
	Issues int64 `json:"issues,omitempty"`
	Releases int64 `json:"releases,omitempty"`
}

type QuotaUsedSizeAssetsPackages struct {
	All int64 `json:"all,omitempty"`
}

type QuotaUsedSizeGit struct {
	LFS int64 `json:"LFS,omitempty"`
}

type QuotaUsedSizeRepos struct {
	Private int64 `json:"private,omitempty"`
	Public int64 `json:"public,omitempty"`
}

type Reaction struct {
	Content string `json:"content,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	User *User `json:"user,omitempty"`
}

type Reference struct {
	Object *GitObject `json:"object,omitempty"`
	Ref string `json:"ref,omitempty"`
	Url string `json:"url,omitempty"`
}

type RegisterRunnerOptions struct {
	Description string `json:"description,omitempty"`
	Ephemeral bool `json:"ephemeral,omitempty"`
	Name string `json:"name,omitempty"`
}

type RegisterRunnerResponse struct {
	Id int64 `json:"id,omitempty"`
	Token string `json:"token,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}

type RegistrationToken struct {
	Token string `json:"token,omitempty"`
}

type Release struct {
	ArchiveDownloadCount *TagArchiveDownloadCount `json:"archive_download_count,omitempty"`
	Assets []*Attachment `json:"assets,omitempty"`
	Author *User `json:"author,omitempty"`
	Body string `json:"body,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Draft bool `json:"draft,omitempty"`
	HideArchiveLinks bool `json:"hide_archive_links,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Prerelease bool `json:"prerelease,omitempty"`
	PublishedAt *time.Time `json:"published_at,omitempty"`
	TagName string `json:"tag_name,omitempty"`
	TarballUrl string `json:"tarball_url,omitempty"`
	TargetCommitish string `json:"target_commitish,omitempty"`
	UploadUrl string `json:"upload_url,omitempty"`
	Url string `json:"url,omitempty"`
	ZipballUrl string `json:"zipball_url,omitempty"`
}

type RenameOrgOption struct {
	NewName string `json:"new_name,omitempty"`
}

type RenameUserOption struct {
	NewUsername string `json:"new_username,omitempty"`
}

type ReplaceFlagsOption struct {
	Flags []string `json:"flags,omitempty"`
}

type RepoCollaboratorPermission struct {
	Permission string `json:"permission,omitempty"`
	RoleName string `json:"role_name,omitempty"`
	User *User `json:"user,omitempty"`
}

type RepoCommit struct {
	Author *CommitUser `json:"author,omitempty"`
	Committer *CommitUser `json:"committer,omitempty"`
	Message string `json:"message,omitempty"`
	Tree *CommitMeta `json:"tree,omitempty"`
	Url string `json:"url,omitempty"`
	Verification *PayloadCommitVerification `json:"verification,omitempty"`
}

type RepoTargetOption struct {
	Name string `json:"name,omitempty"`
	Owner string `json:"owner,omitempty"`
}

type RepoTopicOptions struct {
	Topics []string `json:"topics,omitempty"`
}

type RepoTransfer struct {
	Doer *User `json:"doer,omitempty"`
	Recipient *User `json:"recipient,omitempty"`
	Teams []*Team `json:"teams,omitempty"`
}

type Repository struct {
	AllowFastForwardOnlyMerge bool `json:"allow_fast_forward_only_merge,omitempty"`
	AllowMergeCommits bool `json:"allow_merge_commits,omitempty"`
	AllowRebase bool `json:"allow_rebase,omitempty"`
	AllowRebaseExplicit bool `json:"allow_rebase_explicit,omitempty"`
	AllowRebaseUpdate bool `json:"allow_rebase_update,omitempty"`
	AllowSquashMerge bool `json:"allow_squash_merge,omitempty"`
	Archived bool `json:"archived,omitempty"`
	ArchivedAt *time.Time `json:"archived_at,omitempty"`
	AvatarUrl string `json:"avatar_url,omitempty"`
	CloneUrl string `json:"clone_url,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DefaultAllowMaintainerEdit bool `json:"default_allow_maintainer_edit,omitempty"`
	DefaultBranch string `json:"default_branch,omitempty"`
	DefaultDeleteBranchAfterMerge bool `json:"default_delete_branch_after_merge,omitempty"`
	DefaultMergeStyle string `json:"default_merge_style,omitempty"`
	DefaultUpdateStyle string `json:"default_update_style,omitempty"`
	Description string `json:"description,omitempty"`
	Empty bool `json:"empty,omitempty"`
	ExternalTracker *ExternalTracker `json:"external_tracker,omitempty"`
	ExternalWiki *ExternalWiki `json:"external_wiki,omitempty"`
	Fork bool `json:"fork,omitempty"`
	ForksCount int64 `json:"forks_count,omitempty"`
	FullName string `json:"full_name,omitempty"`
	GloballyEditableWiki bool `json:"globally_editable_wiki,omitempty"`
	HasActions bool `json:"has_actions,omitempty"`
	HasIssues bool `json:"has_issues,omitempty"`
	HasPackages bool `json:"has_packages,omitempty"`
	HasProjects bool `json:"has_projects,omitempty"`
	HasPullRequests bool `json:"has_pull_requests,omitempty"`
	HasReleases bool `json:"has_releases,omitempty"`
	HasWiki bool `json:"has_wiki,omitempty"`
	HasWikiContents bool `json:"has_wiki_contents,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	IgnoreWhitespaceConflicts bool `json:"ignore_whitespace_conflicts,omitempty"`
	Internal bool `json:"internal,omitempty"`
	InternalTracker *InternalTracker `json:"internal_tracker,omitempty"`
	Language string `json:"language,omitempty"`
	LanguagesUrl string `json:"languages_url,omitempty"`
	Link string `json:"link,omitempty"`
	Mirror bool `json:"mirror,omitempty"`
	MirrorInterval string `json:"mirror_interval,omitempty"`
	MirrorUpdated *time.Time `json:"mirror_updated,omitempty"`
	Name string `json:"name,omitempty"`
	ObjectFormatName string `json:"object_format_name,omitempty"`
	OpenIssuesCount int64 `json:"open_issues_count,omitempty"`
	OpenPrCounter int64 `json:"open_pr_counter,omitempty"`
	OriginalUrl string `json:"original_url,omitempty"`
	Owner *User `json:"owner,omitempty"`
	Parent *Repository `json:"parent,omitempty"`
	Permissions *Permission `json:"permissions,omitempty"`
	Private bool `json:"private,omitempty"`
	ReleaseCounter int64 `json:"release_counter,omitempty"`
	RepoTransfer *RepoTransfer `json:"repo_transfer,omitempty"`
	Size int64 `json:"size,omitempty"`
	SshUrl string `json:"ssh_url,omitempty"`
	StarsCount int64 `json:"stars_count,omitempty"`
	Template bool `json:"template,omitempty"`
	Topics []string `json:"topics,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
	WatchersCount int64 `json:"watchers_count,omitempty"`
	Website string `json:"website,omitempty"`
	WikiBranch string `json:"wiki_branch,omitempty"`
	WikiCloneUrl string `json:"wiki_clone_url,omitempty"`
	WikiSshUrl string `json:"wiki_ssh_url,omitempty"`
}

type RepositoryMeta struct {
	FullName string `json:"full_name,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Owner string `json:"owner,omitempty"`
}

type ReviewStateType string

type SearchResults struct {
	Data []*Repository `json:"data,omitempty"`
	Ok bool `json:"ok,omitempty"`
}

type Secret struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Name string `json:"name,omitempty"`
}

type ServerVersion struct {
	Version string `json:"version,omitempty"`
}

type SetUserQuotaGroupsOptions struct {
	Groups []string `json:"groups,omitempty"`
}

type StateType string

type StopWatch struct {
	Created *time.Time `json:"created,omitempty"`
	Duration string `json:"duration,omitempty"`
	IssueIndex int64 `json:"issue_index,omitempty"`
	IssueTitle string `json:"issue_title,omitempty"`
	RepoName string `json:"repo_name,omitempty"`
	RepoOwnerName string `json:"repo_owner_name,omitempty"`
	Seconds int64 `json:"seconds,omitempty"`
}

type SubmitPullReviewOptions struct {
	Body string `json:"body,omitempty"`
	Event *ReviewStateType `json:"event,omitempty"`
}

type SyncForkInfo struct {
	Allowed bool `json:"allowed,omitempty"`
	BaseCommit string `json:"base_commit,omitempty"`
	CommitsBehind int64 `json:"commits_behind,omitempty"`
	ForkCommit string `json:"fork_commit,omitempty"`
}

type Tag struct {
	ArchiveDownloadCount *TagArchiveDownloadCount `json:"archive_download_count,omitempty"`
	Commit *CommitMeta `json:"commit,omitempty"`
	Id string `json:"id,omitempty"`
	Message string `json:"message,omitempty"`
	Name string `json:"name,omitempty"`
	TarballUrl string `json:"tarball_url,omitempty"`
	ZipballUrl string `json:"zipball_url,omitempty"`
}

type TagArchiveDownloadCount struct {
	TarGz int64 `json:"tar_gz,omitempty"`
	Zip int64 `json:"zip,omitempty"`
}

type TagProtection struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id int64 `json:"id,omitempty"`
	NamePattern string `json:"name_pattern,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	WhitelistTeams []string `json:"whitelist_teams,omitempty"`
	WhitelistUsernames []string `json:"whitelist_usernames,omitempty"`
}

type Team struct {
	CanCreateOrgRepo bool `json:"can_create_org_repo,omitempty"`
	Description string `json:"description,omitempty"`
	Id int64 `json:"id,omitempty"`
	IncludesAllRepositories bool `json:"includes_all_repositories,omitempty"`
	Name string `json:"name,omitempty"`
	Organization *Organization `json:"organization,omitempty"`
	Permission string `json:"permission,omitempty"`
	Units []string `json:"units,omitempty"`
	UnitsMap map[string]string `json:"units_map,omitempty"`
}

type TimeStamp int64

type TimelineComment struct {
	Assignee *User `json:"assignee,omitempty"`
	AssigneeTeam *Team `json:"assignee_team,omitempty"`
	Body string `json:"body,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DependentIssue *Issue `json:"dependent_issue,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	IssueUrl string `json:"issue_url,omitempty"`
	Label *Label `json:"label,omitempty"`
	Milestone *Milestone `json:"milestone,omitempty"`
	NewRef string `json:"new_ref,omitempty"`
	NewTitle string `json:"new_title,omitempty"`
	OldMilestone *Milestone `json:"old_milestone,omitempty"`
	OldProjectId int64 `json:"old_project_id,omitempty"`
	OldRef string `json:"old_ref,omitempty"`
	OldTitle string `json:"old_title,omitempty"`
	ProjectId int64 `json:"project_id,omitempty"`
	PullRequestUrl string `json:"pull_request_url,omitempty"`
	RefAction string `json:"ref_action,omitempty"`
	RefComment *Comment `json:"ref_comment,omitempty"`
	RefCommitSha string `json:"ref_commit_sha,omitempty"`
	RefIssue *Issue `json:"ref_issue,omitempty"`
	RemovedAssignee bool `json:"removed_assignee,omitempty"`
	ResolveDoer *User `json:"resolve_doer,omitempty"`
	ReviewId int64 `json:"review_id,omitempty"`
	TrackedTime *TrackedTime `json:"tracked_time,omitempty"`
	Type_ string `json:"type,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	User *User `json:"user,omitempty"`
}

type TopicName struct {
	Topics []string `json:"topics,omitempty"`
}

type TopicResponse struct {
	Created *time.Time `json:"created,omitempty"`
	Id int64 `json:"id,omitempty"`
	RepoCount int64 `json:"repo_count,omitempty"`
	TopicName string `json:"topic_name,omitempty"`
	Updated *time.Time `json:"updated,omitempty"`
}

type TrackedTime struct {
	Created *time.Time `json:"created,omitempty"`
	Id int64 `json:"id,omitempty"`
	Issue *Issue `json:"issue,omitempty"`
	IssueId int64 `json:"issue_id,omitempty"`
	Time int64 `json:"time,omitempty"`
	UserId int64 `json:"user_id,omitempty"`
	UserName string `json:"user_name,omitempty"`
}

type TransferRepoOption struct {
	NewOwner string `json:"new_owner,omitempty"`
	TeamIds []int64 `json:"team_ids,omitempty"`
}

type UpdateBranchRepoOption struct {
	Name string `json:"name,omitempty"`
}

type UpdateFileOptions struct {
	Author *Identity `json:"author,omitempty"`
	Branch string `json:"branch,omitempty"`
	Committer *Identity `json:"committer,omitempty"`
	Content string `json:"content,omitempty"`
	Dates *CommitDateOptions `json:"dates,omitempty"`
	ForceOverwriteNewBranch bool `json:"force_overwrite_new_branch,omitempty"`
	FromPath string `json:"from_path,omitempty"`
	Message string `json:"message,omitempty"`
	NewBranch string `json:"new_branch,omitempty"`
	Sha string `json:"sha,omitempty"`
	Signoff bool `json:"signoff,omitempty"`
}

type UpdateRepoAvatarOption struct {
	Image string `json:"image,omitempty"`
}

type UpdateUserAvatarOption struct {
	Image string `json:"image,omitempty"`
}

type UpdateVariableOption struct {
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}

type User struct {
	Active bool `json:"active,omitempty"`
	AvatarUrl string `json:"avatar_url,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	Description string `json:"description,omitempty"`
	Email string `json:"email,omitempty"`
	FollowersCount int64 `json:"followers_count,omitempty"`
	FollowingCount int64 `json:"following_count,omitempty"`
	FullName string `json:"full_name,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	Id int64 `json:"id,omitempty"`
	IsAdmin bool `json:"is_admin,omitempty"`
	Language string `json:"language,omitempty"`
	LastLogin *time.Time `json:"last_login,omitempty"`
	Location string `json:"location,omitempty"`
	Login string `json:"login,omitempty"`
	LoginName string `json:"login_name,omitempty"`
	ProhibitLogin bool `json:"prohibit_login,omitempty"`
	Pronouns string `json:"pronouns,omitempty"`
	Restricted bool `json:"restricted,omitempty"`
	SourceId int64 `json:"source_id,omitempty"`
	StarredReposCount int64 `json:"starred_repos_count,omitempty"`
	Visibility string `json:"visibility,omitempty"`
	Website string `json:"website,omitempty"`
}

type UserHeatmapData struct {
	Contributions int64 `json:"contributions,omitempty"`
	Timestamp *TimeStamp `json:"timestamp,omitempty"`
}

type UserSettings struct {
	Description string `json:"description,omitempty"`
	DiffViewStyle string `json:"diff_view_style,omitempty"`
	EnableRepoUnitHints bool `json:"enable_repo_unit_hints,omitempty"`
	FullName string `json:"full_name,omitempty"`
	HideActivity bool `json:"hide_activity,omitempty"`
	HideEmail bool `json:"hide_email,omitempty"`
	HidePronouns bool `json:"hide_pronouns,omitempty"`
	Language string `json:"language,omitempty"`
	Location string `json:"location,omitempty"`
	Pronouns string `json:"pronouns,omitempty"`
	Theme string `json:"theme,omitempty"`
	Website string `json:"website,omitempty"`
}

type UserSettingsOptions struct {
	Description string `json:"description,omitempty"`
	DiffViewStyle string `json:"diff_view_style,omitempty"`
	EnableRepoUnitHints bool `json:"enable_repo_unit_hints,omitempty"`
	FullName string `json:"full_name,omitempty"`
	HideActivity bool `json:"hide_activity,omitempty"`
	HideEmail bool `json:"hide_email,omitempty"`
	HidePronouns bool `json:"hide_pronouns,omitempty"`
	Language string `json:"language,omitempty"`
	Location string `json:"location,omitempty"`
	Pronouns string `json:"pronouns,omitempty"`
	Theme string `json:"theme,omitempty"`
	Website string `json:"website,omitempty"`
}

type VerifyGPGKeyOption struct {
	ArmoredSignature string `json:"armored_signature,omitempty"`
	KeyId string `json:"key_id,omitempty"`
}

type WatchInfo struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Ignored bool `json:"ignored,omitempty"`
	Reason interface{} `json:"reason,omitempty"`
	RepositoryUrl string `json:"repository_url,omitempty"`
	Subscribed bool `json:"subscribed,omitempty"`
	Url string `json:"url,omitempty"`
}

type WikiCommit struct {
	Author *CommitUser `json:"author,omitempty"`
	Commiter *CommitUser `json:"commiter,omitempty"`
	Message string `json:"message,omitempty"`
	Sha string `json:"sha,omitempty"`
}

type WikiCommitList struct {
	Commits []*WikiCommit `json:"commits,omitempty"`
	Count int64 `json:"count,omitempty"`
}

type WikiPage struct {
	CommitCount int64 `json:"commit_count,omitempty"`
	ContentBase64 string `json:"content_base64,omitempty"`
	Footer string `json:"footer,omitempty"`
	HtmlUrl string `json:"html_url,omitempty"`
	LastCommit *WikiCommit `json:"last_commit,omitempty"`
	Sidebar string `json:"sidebar,omitempty"`
	SubUrl string `json:"sub_url,omitempty"`
	Title string `json:"title,omitempty"`
}

type WikiPageMetaData struct {
	HtmlUrl string `json:"html_url,omitempty"`
	LastCommit *WikiCommit `json:"last_commit,omitempty"`
	SubUrl string `json:"sub_url,omitempty"`
	Title string `json:"title,omitempty"`
}

