// Code generated by api/gen. DO NOT EDIT.

package forgejo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// ActivitypubInstanceActor — Returns the instance's Actor
// GET /activitypub/actor
func (s *ActivitypubService) ActivitypubInstanceActor(ctx context.Context) (*ActivityPub, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/actor"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActivityPub
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// ActivitypubInstanceActorInbox — Send to the inbox
// POST /activitypub/actor/inbox
func (s *ActivitypubService) ActivitypubInstanceActorInbox(ctx context.Context) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/actor/inbox"))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// ActivitypubInstanceActorOutbox — Display the outbox (always empty)
// POST /activitypub/actor/outbox
func (s *ActivitypubService) ActivitypubInstanceActorOutbox(ctx context.Context) (*ForgeOutbox, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/actor/outbox"))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ForgeOutbox
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// ActivitypubPerson — Returns the Person actor for a user
// GET /activitypub/user-id/{user-id}
func (s *ActivitypubService) ActivitypubPerson(ctx context.Context, userId int64) (*ActivityPub, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/user-id/%d", userId))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActivityPub
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// ActivitypubPersonActivity — Get a specific activity of the user
// GET /activitypub/user-id/{user-id}/activities/{activity-id}/activity
func (s *ActivitypubService) ActivitypubPersonActivity(ctx context.Context, userId int, activityId int) (*ActivityPub, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/user-id/%d/activities/%d/activity", userId, activityId))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActivityPub
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// ActivitypubPersonActivityNote — Get a specific activity object of the user
// GET /activitypub/user-id/{user-id}/activities/{activity-id}
func (s *ActivitypubService) ActivitypubPersonActivityNote(ctx context.Context, userId int, activityId int) (*ActivityPub, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/user-id/%d/activities/%d", userId, activityId))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActivityPub
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// ActivitypubPersonFeed — List the user's recorded activity
// GET /activitypub/user-id/{user-id}/outbox
func (s *ActivitypubService) ActivitypubPersonFeed(ctx context.Context, userId int) (*ForgeOutbox, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/user-id/%d/outbox", userId))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ForgeOutbox
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// ActivitypubPersonInbox — Send to the inbox
// POST /activitypub/user-id/{user-id}/inbox
func (s *ActivitypubService) ActivitypubPersonInbox(ctx context.Context, userId int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/user-id/%d/inbox", userId))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// ActivitypubRepository — Returns the Repository actor for a repo
// GET /activitypub/repository-id/{repository-id}
func (s *ActivitypubService) ActivitypubRepository(ctx context.Context, repositoryId int64) (*ActivityPub, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/repository-id/%d", repositoryId))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActivityPub
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// ActivitypubRepositoryInbox — Send to the inbox
// POST /activitypub/repository-id/{repository-id}/inbox
func (s *ActivitypubService) ActivitypubRepositoryInbox(ctx context.Context, repositoryId int64, body *ForgeLike) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/repository-id/%d/inbox", repositoryId))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// ActivitypubRepositoryOutbox — Display the outbox
// POST /activitypub/repository-id/{repository-id}/outbox
func (s *ActivitypubService) ActivitypubRepositoryOutbox(ctx context.Context, repositoryId int64) (*ForgeOutbox, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/activitypub/repository-id/%d/outbox", repositoryId))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ForgeOutbox
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

