// Code generated by api/gen. DO NOT EDIT.

package forgejo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// CreateOrgRepo — Create a repository in an organization
// POST /orgs/{org}/repos
func (s *OrgService) CreateOrgRepo(ctx context.Context, org string, body *CreateRepoOption) (*Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/repos", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// CreateOrgVariable — Create a new variable in organization
// POST /orgs/{org}/actions/variables/{variablename}
func (s *OrgService) CreateOrgVariable(ctx context.Context, org string, variablename string, body *CreateVariableOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/variables/%s", org, variablename))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// DeleteOrgRunner — Delete a particular runner that belongs to the organization
// DELETE /orgs/{org}/actions/runners/{runner_id}
func (s *OrgService) DeleteOrgRunner(ctx context.Context, org string, runnerId string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/runners/%s", org, runnerId))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// DeleteOrgSecret — Delete a secret in an organization
// DELETE /orgs/{org}/actions/secrets/{secretname}
func (s *OrgService) DeleteOrgSecret(ctx context.Context, org string, secretname string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/secrets/%s", org, secretname))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// DeleteOrgVariable — Delete organization's variable by name
// DELETE /orgs/{org}/actions/variables/{variablename}
func (s *OrgService) DeleteOrgVariable(ctx context.Context, org string, variablename string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/variables/%s", org, variablename))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// GetOrgRunner — Get a particular runner that belongs to the organization
// GET /orgs/{org}/actions/runners/{runner_id}
func (s *OrgService) GetOrgRunner(ctx context.Context, org string, runnerId string) (*ActionRunner, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/runners/%s", org, runnerId))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActionRunner
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetOrgRunners — Get the organization's runners
// GET /orgs/{org}/actions/runners
func (s *OrgService) GetOrgRunners(ctx context.Context, org string, visible bool, page int, limit int) ([]ActionRunner, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/runners", org))
	qry := u.Query()
	if visible != false { qry.Set("visible", fmt.Sprintf("visible", %!s(MISSING))) }
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []ActionRunner
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// GetOrgVariable — Get organization's variable by name
// GET /orgs/{org}/actions/variables/{variablename}
func (s *OrgService) GetOrgVariable(ctx context.Context, org string, variablename string) (*ActionVariable, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/variables/%s", org, variablename))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActionVariable
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetOrgVariablesList — List variables of an organization
// GET /orgs/{org}/actions/variables
func (s *OrgService) GetOrgVariablesList(ctx context.Context, org string, page int, limit int) ([]ActionVariable, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/variables", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []ActionVariable
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgBlockUser — Blocks a user from the organization
// PUT /orgs/{org}/block/{username}
func (s *OrgService) OrgBlockUser(ctx context.Context, org string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/block/%s", org, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgCheckQuota — Check if the organization is over quota for a given subject
// GET /orgs/{org}/quota/check
func (s *OrgService) OrgCheckQuota(ctx context.Context, org string, subject string) (bool, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/quota/check", org))
	qry := u.Query()
	if subject != "" { qry.Set("subject", fmt.Sprintf("subject", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return false, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return false, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return false, nil, handleError(resp) }

	var result bool
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return false,  nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgConcealMember — Conceal a user's membership
// DELETE /orgs/{org}/public_members/{username}
func (s *OrgService) OrgConcealMember(ctx context.Context, org string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/public_members/%s", org, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgCreate — Create an organization
// POST /orgs
func (s *OrgService) OrgCreate(ctx context.Context, organization *CreateOrgOption) (*Organization, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs"))
	bodyBytes, err := json.Marshal(organization)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Organization
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgCreateHook — Create a hook
// POST /orgs/{org}/hooks
func (s *OrgService) OrgCreateHook(ctx context.Context, org string, body *CreateHookOption) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/hooks", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgCreateLabel — Create a label for an organization
// POST /orgs/{org}/labels
func (s *OrgService) OrgCreateLabel(ctx context.Context, org string, body *CreateLabelOption) (*Label, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/labels", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Label
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgCreateTeam — Create a team
// POST /orgs/{org}/teams
func (s *OrgService) OrgCreateTeam(ctx context.Context, org string, body *CreateTeamOption) (*Team, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/teams", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Team
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgDelete — Delete an organization
// DELETE /orgs/{org}
func (s *OrgService) OrgDelete(ctx context.Context, org string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s", org))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgDeleteAvatar — Delete an organization's avatar. It will be replaced by a default one
// DELETE /orgs/{org}/avatar
func (s *OrgService) OrgDeleteAvatar(ctx context.Context, org string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/avatar", org))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgDeleteHook — Delete a hook
// DELETE /orgs/{org}/hooks/{id}
func (s *OrgService) OrgDeleteHook(ctx context.Context, org string, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/hooks/%d", org, id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgDeleteLabel — Delete a label
// DELETE /orgs/{org}/labels/{id}
func (s *OrgService) OrgDeleteLabel(ctx context.Context, org string, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/labels/%d", org, id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgDeleteMember — Remove a member from an organization
// DELETE /orgs/{org}/members/{username}
func (s *OrgService) OrgDeleteMember(ctx context.Context, org string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/members/%s", org, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgEdit — Edit an organization
// PATCH /orgs/{org}
func (s *OrgService) OrgEdit(ctx context.Context, org string, body *EditOrgOption) (*Organization, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Organization
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgEditHook — Update a hook
// PATCH /orgs/{org}/hooks/{id}
func (s *OrgService) OrgEditHook(ctx context.Context, org string, id int64, body *EditHookOption) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/hooks/%d", org, id))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgEditLabel — Update a label
// PATCH /orgs/{org}/labels/{id}
func (s *OrgService) OrgEditLabel(ctx context.Context, org string, id int64, body *EditLabelOption) (*Label, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/labels/%d", org, id))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Label
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgGet — Get an organization
// GET /orgs/{org}
func (s *OrgService) OrgGet(ctx context.Context, org string) (*Organization, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s", org))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Organization
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgGetAll — List all organizations
// GET /orgs
func (s *OrgService) OrgGetAll(ctx context.Context, page int, limit int) ([]Organization, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Organization
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgGetHook — Get a hook
// GET /orgs/{org}/hooks/{id}
func (s *OrgService) OrgGetHook(ctx context.Context, org string, id int64) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/hooks/%d", org, id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgGetLabel — Get a single label
// GET /orgs/{org}/labels/{id}
func (s *OrgService) OrgGetLabel(ctx context.Context, org string, id int64) (*Label, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/labels/%d", org, id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Label
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgGetQuota — Get quota information for an organization
// GET /orgs/{org}/quota
func (s *OrgService) OrgGetQuota(ctx context.Context, org string) (*QuotaInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/quota", org))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result QuotaInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgGetRunnerRegistrationToken — Get the organization's runner registration token
// GET /orgs/{org}/actions/runners/registration-token
func (s *OrgService) OrgGetRunnerRegistrationToken(ctx context.Context, org string) (*RegistrationToken, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/runners/registration-token", org))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result RegistrationToken
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgIsMember — Check if a user is a member of an organization
// GET /orgs/{org}/members/{username}
func (s *OrgService) OrgIsMember(ctx context.Context, org string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/members/%s", org, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgIsPublicMember — Check if a user is a public member of an organization
// GET /orgs/{org}/public_members/{username}
func (s *OrgService) OrgIsPublicMember(ctx context.Context, org string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/public_members/%s", org, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgListActionsSecrets — List actions secrets of an organization
// GET /orgs/{org}/actions/secrets
func (s *OrgService) OrgListActionsSecrets(ctx context.Context, org string, page int, limit int) ([]Secret, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/secrets", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Secret
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListActivityFeeds — List an organization's activity feeds
// GET /orgs/{org}/activities/feeds
func (s *OrgService) OrgListActivityFeeds(ctx context.Context, org string, date string, page int, limit int) ([]Activity, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/activities/feeds", org))
	qry := u.Query()
	if date != "" { qry.Set("date", fmt.Sprintf("date", %!s(MISSING))) }
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Activity
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListBlockedUsers — List the organization's blocked users
// GET /orgs/{org}/list_blocked
func (s *OrgService) OrgListBlockedUsers(ctx context.Context, org string, page int, limit int) ([]BlockedUser, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/list_blocked", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []BlockedUser
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListHooks — List an organization's webhooks
// GET /orgs/{org}/hooks
func (s *OrgService) OrgListHooks(ctx context.Context, org string, page int, limit int) ([]Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/hooks", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListLabels — List an organization's labels
// GET /orgs/{org}/labels
func (s *OrgService) OrgListLabels(ctx context.Context, org string, sort string, page int, limit int) ([]Label, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/labels", org))
	qry := u.Query()
	if sort != "" { qry.Set("sort", fmt.Sprintf("sort", %!s(MISSING))) }
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Label
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListMembers — List an organization's members
// GET /orgs/{org}/members
func (s *OrgService) OrgListMembers(ctx context.Context, org string, page int, limit int) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/members", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListPublicMembers — List an organization's public members
// GET /orgs/{org}/public_members
func (s *OrgService) OrgListPublicMembers(ctx context.Context, org string, page int, limit int) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/public_members", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListQuotaArtifacts — List the artifacts affecting the organization's quota
// GET /orgs/{org}/quota/artifacts
func (s *OrgService) OrgListQuotaArtifacts(ctx context.Context, org string, page int, limit int) (*QuotaUsedArtifactList, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/quota/artifacts", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result QuotaUsedArtifactList
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgListQuotaAttachments — List the attachments affecting the organization's quota
// GET /orgs/{org}/quota/attachments
func (s *OrgService) OrgListQuotaAttachments(ctx context.Context, org string, page int, limit int) (*QuotaUsedAttachmentList, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/quota/attachments", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result QuotaUsedAttachmentList
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgListQuotaPackages — List the packages affecting the organization's quota
// GET /orgs/{org}/quota/packages
func (s *OrgService) OrgListQuotaPackages(ctx context.Context, org string, page int, limit int) (*QuotaUsedPackageList, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/quota/packages", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result QuotaUsedPackageList
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgListRepos — List an organization's repos
// GET /orgs/{org}/repos
func (s *OrgService) OrgListRepos(ctx context.Context, org string, page int, limit int) ([]Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/repos", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListTeams — List an organization's teams
// GET /orgs/{org}/teams
func (s *OrgService) OrgListTeams(ctx context.Context, org string, page int, limit int) ([]Team, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/teams", org))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Team
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgPublicizeMember — Publicize a user's membership
// PUT /orgs/{org}/public_members/{username}
func (s *OrgService) OrgPublicizeMember(ctx context.Context, org string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/public_members/%s", org, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgSearchRunJobs — Search for organization's action jobs according filter conditions
// GET /orgs/{org}/actions/runners/jobs
func (s *OrgService) OrgSearchRunJobs(ctx context.Context, org string, labels string) ([]ActionRunJob, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/runners/jobs", org))
	qry := u.Query()
	if labels != "" { qry.Set("labels", fmt.Sprintf("labels", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []ActionRunJob
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgUnblockUser — Unblock a user from the organization
// PUT /orgs/{org}/unblock/{username}
func (s *OrgService) OrgUnblockUser(ctx context.Context, org string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/unblock/%s", org, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgUpdateAvatar — Update an organization's avatar
// POST /orgs/{org}/avatar
func (s *OrgService) OrgUpdateAvatar(ctx context.Context, org string, body *UpdateUserAvatarOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/avatar", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// RegisterOrgRunner — Register a new organization-level runner
// POST /orgs/{org}/actions/runners
func (s *OrgService) RegisterOrgRunner(ctx context.Context, org string, body *RegisterRunnerOptions) (*RegisterRunnerResponse, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/runners", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result RegisterRunnerResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// RenameOrg — Rename an organization
// POST /orgs/{org}/rename
func (s *OrgService) RenameOrg(ctx context.Context, org string, body *RenameOrgOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/rename", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// TeamSearch — Search for teams within an organization
// GET /orgs/{org}/teams/search
func (s *OrgService) TeamSearch(ctx context.Context, org string, q string, includeDesc bool, page int, limit int) (*interface{}, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/teams/search", org))
	qry := u.Query()
	if q != "" { qry.Set("q", fmt.Sprintf("q", %!s(MISSING))) }
	if includeDesc != false { qry.Set("include_desc", fmt.Sprintf("includeDesc", %!s(MISSING))) }
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UpdateOrgSecret — Create or Update a secret value in an organization
// PUT /orgs/{org}/actions/secrets/{secretname}
func (s *OrgService) UpdateOrgSecret(ctx context.Context, org string, secretname string, body *CreateOrUpdateSecretOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/secrets/%s", org, secretname))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UpdateOrgVariable — Update variable in organization
// PUT /orgs/{org}/actions/variables/{variablename}
func (s *OrgService) UpdateOrgVariable(ctx context.Context, org string, variablename string, body *UpdateVariableOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/orgs/%s/actions/variables/%s", org, variablename))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

