// Code generated by api/gen. DO NOT EDIT.

package forgejo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// CreateCurrentUserRepo — Create a repository
// POST /user/repos
func (s *MiscService) CreateCurrentUserRepo(ctx context.Context, body *CreateRepoOption) (*Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/repos"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// CreateOrgRepoDeprecated — Create a repository in an organization
// POST /org/{org}/repos
func (s *MiscService) CreateOrgRepoDeprecated(ctx context.Context, org string, body *CreateRepoOption) (*Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/org/%s/repos", org))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// CreateUserVariable — Create a user-level variable
// POST /user/actions/variables/{variablename}
func (s *MiscService) CreateUserVariable(ctx context.Context, variablename string, body *CreateVariableOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/variables/%s", variablename))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// DeletePackage — Delete a package
// DELETE /packages/{owner}/{type}/{name}/{version}
func (s *MiscService) DeletePackage(ctx context.Context, owner string, type_ string, name string, version string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/packages/%s/%s/%s/%s", owner, type_, name, version))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// DeleteUserRunner — Delete a particular user-level runner
// DELETE /user/actions/runners/{runner_id}
func (s *MiscService) DeleteUserRunner(ctx context.Context, runnerId string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/runners/%s", runnerId))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// DeleteUserSecret — Delete a secret in a user scope
// DELETE /user/actions/secrets/{secretname}
func (s *MiscService) DeleteUserSecret(ctx context.Context, secretname string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/secrets/%s", secretname))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// DeleteUserVariable — Delete a user-level variable which is created by current doer
// DELETE /user/actions/variables/{variablename}
func (s *MiscService) DeleteUserVariable(ctx context.Context, variablename string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/variables/%s", variablename))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// GetActionsRun — Get a workflow run associated with a token
// GET /actions/run
func (s *MiscService) GetActionsRun(ctx context.Context) (*ActionRun, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/actions/run"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActionRun
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetGeneralAPISettings — Get instance's global settings for api
// GET /settings/api
func (s *MiscService) GetGeneralAPISettings(ctx context.Context) (*GeneralAPISettings, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/settings/api"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result GeneralAPISettings
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetGeneralAttachmentSettings — Get instance's global settings for Attachment
// GET /settings/attachment
func (s *MiscService) GetGeneralAttachmentSettings(ctx context.Context) (*GeneralAttachmentSettings, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/settings/attachment"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result GeneralAttachmentSettings
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetGeneralRepositorySettings — Get instance's global settings for repositories
// GET /settings/repository
func (s *MiscService) GetGeneralRepositorySettings(ctx context.Context) (*GeneralRepoSettings, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/settings/repository"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result GeneralRepoSettings
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetGeneralUISettings — Get instance's global settings for ui
// GET /settings/ui
func (s *MiscService) GetGeneralUISettings(ctx context.Context) (*GeneralUISettings, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/settings/ui"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result GeneralUISettings
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetGitignoreTemplateInfo — Returns information about a gitignore template
// GET /gitignore/templates/{name}
func (s *MiscService) GetGitignoreTemplateInfo(ctx context.Context, name string) (*GitignoreTemplateInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/gitignore/templates/%s", name))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result GitignoreTemplateInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetLabelTemplateInfo — Returns all labels in a template
// GET /label/templates/{name}
func (s *MiscService) GetLabelTemplateInfo(ctx context.Context, name string) ([]LabelTemplate, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/label/templates/%s", name))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []LabelTemplate
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// GetLicenseTemplateInfo — Returns information about a license template
// GET /licenses/{name}
func (s *MiscService) GetLicenseTemplateInfo(ctx context.Context, name string) (*LicenseTemplateInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/licenses/%s", name))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result LicenseTemplateInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetNodeInfo — Returns the nodeinfo of the Forgejo application
// GET /nodeinfo
func (s *MiscService) GetNodeInfo(ctx context.Context) (*NodeInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/nodeinfo"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result NodeInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetPackage — Gets a package
// GET /packages/{owner}/{type}/{name}/{version}
func (s *MiscService) GetPackage(ctx context.Context, owner string, type_ string, name string, version string) (*Package, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/packages/%s/%s/%s/%s", owner, type_, name, version))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Package
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetSSHSigningKey — Get default signing-key.ssh
// GET /signing-key.ssh
func (s *MiscService) GetSSHSigningKey(ctx context.Context) (string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/signing-key.ssh"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return "", nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return "", nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return "", nil, handleError(resp) }

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil { return "", nil, fmt.Errorf("read: %w", err) }
	return string(rawBody), &Response{Response: resp}, nil
}

// GetSigningKey — Get default signing-key.gpg
// GET /signing-key.gpg
func (s *MiscService) GetSigningKey(ctx context.Context) (string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/signing-key.gpg"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return "", nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return "", nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return "", nil, handleError(resp) }

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil { return "", nil, fmt.Errorf("read: %w", err) }
	return string(rawBody), &Response{Response: resp}, nil
}

// GetUserRunner — Get a particular runner that belongs to the user
// GET /user/actions/runners/{runner_id}
func (s *MiscService) GetUserRunner(ctx context.Context, runnerId string) (*ActionRunner, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/runners/%s", runnerId))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActionRunner
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetUserRunners — Get the user's runners
// GET /user/actions/runners
func (s *MiscService) GetUserRunners(ctx context.Context, visible bool, page int, limit int) ([]ActionRunner, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/runners"))
	qry := u.Query()
	if visible != false { qry.Set("visible", fmt.Sprintf("visible", %!s(MISSING))) }
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []ActionRunner
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// GetUserSettings — Get current user's account settings
// GET /user/settings
func (s *MiscService) GetUserSettings(ctx context.Context) (*UserSettings, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/settings"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result UserSettings
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetUserVariable — Get a user-level variable which is created by current doer
// GET /user/actions/variables/{variablename}
func (s *MiscService) GetUserVariable(ctx context.Context, variablename string) (*ActionVariable, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/variables/%s", variablename))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ActionVariable
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// GetUserVariablesList — Get the user-level list of variables which is created by current doer
// GET /user/actions/variables
func (s *MiscService) GetUserVariablesList(ctx context.Context, page int, limit int) ([]ActionVariable, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/variables"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []ActionVariable
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// GetVerificationToken — Get a Token to verify
// GET /user/gpg_key_token
func (s *MiscService) GetVerificationToken(ctx context.Context) (string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/gpg_key_token"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return "", nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return "", nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return "", nil, handleError(resp) }

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil { return "", nil, fmt.Errorf("read: %w", err) }
	return string(rawBody), &Response{Response: resp}, nil
}

// GetVersion — Returns the version of the running application
// GET /version
func (s *MiscService) GetVersion(ctx context.Context) (*ServerVersion, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/version"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result ServerVersion
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// LinkPackage — Link a package to a repository
// POST /packages/{owner}/{type}/{name}/-/link/{repo_name}
func (s *MiscService) LinkPackage(ctx context.Context, owner string, type_ string, name string, repoName string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/packages/%s/%s/%s/-/link/%s", owner, type_, name, repoName))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// ListGitignoresTemplates — Returns a list of all gitignore templates
// GET /gitignore/templates
func (s *MiscService) ListGitignoresTemplates(ctx context.Context) ([]string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/gitignore/templates"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []string
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// ListLabelTemplates — Returns a list of all label templates
// GET /label/templates
func (s *MiscService) ListLabelTemplates(ctx context.Context) ([]string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/label/templates"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []string
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// ListLicenseTemplates — Returns a list of all license templates
// GET /licenses
func (s *MiscService) ListLicenseTemplates(ctx context.Context) ([]LicensesTemplateListEntry, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/licenses"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []LicensesTemplateListEntry
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// ListPackageFiles — Gets all files of a package
// GET /packages/{owner}/{type}/{name}/{version}/files
func (s *MiscService) ListPackageFiles(ctx context.Context, owner string, type_ string, name string, version string) ([]PackageFile, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/packages/%s/%s/%s/%s/files", owner, type_, name, version))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []PackageFile
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// ListPackages — Gets all packages of an owner
// GET /packages/{owner}
func (s *MiscService) ListPackages(ctx context.Context, owner string, page int, limit int, type_ string, q string) ([]Package, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/packages/%s", owner))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	if type_ != "" { qry.Set("type", fmt.Sprintf("type_", %!s(MISSING))) }
	if q != "" { qry.Set("q", fmt.Sprintf("q", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Package
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgAddTeamMember — Add a team member
// PUT /teams/{id}/members/{username}
func (s *MiscService) OrgAddTeamMember(ctx context.Context, id int64, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/members/%s", id, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgAddTeamRepository — Add a repository to a team
// PUT /teams/{id}/repos/{org}/{repo}
func (s *MiscService) OrgAddTeamRepository(ctx context.Context, id int64, org string, repo string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/repos/%s/%s", id, org, repo))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgDeleteTeam — Delete a team
// DELETE /teams/{id}
func (s *MiscService) OrgDeleteTeam(ctx context.Context, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgEditTeam — Edit a team
// PATCH /teams/{id}
func (s *MiscService) OrgEditTeam(ctx context.Context, id int64, body *EditTeamOption) (*Team, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d", id))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Team
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgGetTeam — Get a team
// GET /teams/{id}
func (s *MiscService) OrgGetTeam(ctx context.Context, id int64) (*Team, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Team
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgListCurrentUserOrgs — List the current user's organizations
// GET /user/orgs
func (s *MiscService) OrgListCurrentUserOrgs(ctx context.Context, page int, limit int) ([]Organization, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/orgs"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Organization
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListTeamActivityFeeds — List a team's activity feeds
// GET /teams/{id}/activities/feeds
func (s *MiscService) OrgListTeamActivityFeeds(ctx context.Context, id int64, date string, page int, limit int) ([]Activity, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/activities/feeds", id))
	qry := u.Query()
	if date != "" { qry.Set("date", fmt.Sprintf("date", %!s(MISSING))) }
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Activity
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListTeamMember — List a particular member of team
// GET /teams/{id}/members/{username}
func (s *MiscService) OrgListTeamMember(ctx context.Context, id int64, username string) (*User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/members/%s", id, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgListTeamMembers — List a team's members
// GET /teams/{id}/members
func (s *MiscService) OrgListTeamMembers(ctx context.Context, id int64, page int, limit int) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/members", id))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgListTeamRepo — List a particular repo of team
// GET /teams/{id}/repos/{org}/{repo}
func (s *MiscService) OrgListTeamRepo(ctx context.Context, id int64, org string, repo string) (*Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/repos/%s/%s", id, org, repo))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// OrgListTeamRepos — List a team's repos
// GET /teams/{id}/repos
func (s *MiscService) OrgListTeamRepos(ctx context.Context, id int64, page int, limit int) ([]Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/repos", id))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// OrgRemoveTeamMember — Remove a team member
// DELETE /teams/{id}/members/{username}
func (s *MiscService) OrgRemoveTeamMember(ctx context.Context, id int64, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/members/%s", id, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// OrgRemoveTeamRepository — Remove a repository from a team
// DELETE /teams/{id}/repos/{org}/{repo}
func (s *MiscService) OrgRemoveTeamRepository(ctx context.Context, id int64, org string, repo string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/teams/%d/repos/%s/%s", id, org, repo))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// RegisterUserRunner — Register a new user-level runner
// POST /user/actions/runners
func (s *MiscService) RegisterUserRunner(ctx context.Context, body *RegisterRunnerOptions) (*RegisterRunnerResponse, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/runners"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result RegisterRunnerResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// RenderMarkdown — Render a markdown document as HTML
// POST /markdown
func (s *MiscService) RenderMarkdown(ctx context.Context, body *MarkdownOption) (string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/markdown"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return "", nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return "", nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return "", nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return "", nil, handleError(resp) }

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil { return "", nil, fmt.Errorf("read: %w", err) }
	return string(rawBody), &Response{Response: resp}, nil
}

// RenderMarkdownRaw — Render raw markdown as HTML
// POST /markdown/raw
func (s *MiscService) RenderMarkdownRaw(ctx context.Context, body string) (string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/markdown/raw"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return "", nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return "", nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return "", nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return "", nil, handleError(resp) }

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil { return "", nil, fmt.Errorf("read: %w", err) }
	return string(rawBody), &Response{Response: resp}, nil
}

// RenderMarkup — Render a markup document as HTML
// POST /markup
func (s *MiscService) RenderMarkup(ctx context.Context, body *MarkupOption) (string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/markup"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return "", nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return "", nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return "", nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return "", nil, handleError(resp) }

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil { return "", nil, fmt.Errorf("read: %w", err) }
	return string(rawBody), &Response{Response: resp}, nil
}

// RepoGetByID — Get a repository by id
// GET /repositories/{id}
func (s *MiscService) RepoGetByID(ctx context.Context, id int64) (*Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/repositories/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// TopicSearch — Search for topics by keyword
// GET /topics/search
func (s *MiscService) TopicSearch(ctx context.Context, q string, page int, limit int) (*interface{}, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/topics/search"))
	qry := u.Query()
	if q != "" { qry.Set("q", fmt.Sprintf("q", %!s(MISSING))) }
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UnlinkPackage — Unlink a package from a repository
// POST /packages/{owner}/{type}/{name}/-/unlink
func (s *MiscService) UnlinkPackage(ctx context.Context, owner string, type_ string, name string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/packages/%s/%s/%s/-/unlink", owner, type_, name))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UpdateUserSecret — Create or Update a secret value in a user scope
// PUT /user/actions/secrets/{secretname}
func (s *MiscService) UpdateUserSecret(ctx context.Context, secretname string, body *CreateOrUpdateSecretOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/secrets/%s", secretname))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UpdateUserSettings — Update settings in current user's account
// PATCH /user/settings
func (s *MiscService) UpdateUserSettings(ctx context.Context, body *UserSettingsOptions) (*UserSettings, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/settings"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result UserSettings
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UpdateUserVariable — Update a user-level variable which is created by current doer
// PUT /user/actions/variables/{variablename}
func (s *MiscService) UpdateUserVariable(ctx context.Context, variablename string, body *UpdateVariableOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/variables/%s", variablename))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserAddEmail — Add an email addresses to the current user's account
// POST /user/emails
func (s *MiscService) UserAddEmail(ctx context.Context, body *CreateEmailOption) ([]Email, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/emails"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Email
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserBlockUser — Blocks a user from the doer
// PUT /user/block/{username}
func (s *MiscService) UserBlockUser(ctx context.Context, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/block/%s", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCheckQuota — Check if the authenticated user is over quota for a given subject
// GET /user/quota/check
func (s *MiscService) UserCheckQuota(ctx context.Context, subject string) (bool, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/quota/check"))
	qry := u.Query()
	if subject != "" { qry.Set("subject", fmt.Sprintf("subject", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return false, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return false, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return false, nil, handleError(resp) }

	var result bool
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return false,  nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserCreateHook — Create a hook
// POST /user/hooks
func (s *MiscService) UserCreateHook(ctx context.Context, body *CreateHookOption) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/hooks"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserCreateOAuth2Application — Creates a new OAuth2 application
// POST /user/applications/oauth2
func (s *MiscService) UserCreateOAuth2Application(ctx context.Context, body *CreateOAuth2ApplicationOptions) (*OAuth2Application, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/applications/oauth2"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result OAuth2Application
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserCurrentActivityPubFollow — Follow a remote activitypub account
// POST /user/activitypub/follow
func (s *MiscService) UserCurrentActivityPubFollow(ctx context.Context, body *APRemoteFollowOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/activitypub/follow"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentCheckFollowing — Check whether a user is followed by the authenticated user
// GET /user/following/{username}
func (s *MiscService) UserCurrentCheckFollowing(ctx context.Context, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/following/%s", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentCheckStarring — Whether the authenticated is starring the repo
// GET /user/starred/{owner}/{repo}
func (s *MiscService) UserCurrentCheckStarring(ctx context.Context, owner string, repo string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/starred/%s/%s", owner, repo))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentDeleteFollow — Unfollow a user
// DELETE /user/following/{username}
func (s *MiscService) UserCurrentDeleteFollow(ctx context.Context, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/following/%s", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentDeleteGPGKey — Remove a GPG public key from current user's account
// DELETE /user/gpg_keys/{id}
func (s *MiscService) UserCurrentDeleteGPGKey(ctx context.Context, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/gpg_keys/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentDeleteKey — Delete a public key
// DELETE /user/keys/{id}
func (s *MiscService) UserCurrentDeleteKey(ctx context.Context, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/keys/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentDeleteStar — Unstar the given repo
// DELETE /user/starred/{owner}/{repo}
func (s *MiscService) UserCurrentDeleteStar(ctx context.Context, owner string, repo string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/starred/%s/%s", owner, repo))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentGetGPGKey — Get a GPG key
// GET /user/gpg_keys/{id}
func (s *MiscService) UserCurrentGetGPGKey(ctx context.Context, id int64) (*GPGKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/gpg_keys/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result GPGKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserCurrentGetKey — Get a public key
// GET /user/keys/{id}
func (s *MiscService) UserCurrentGetKey(ctx context.Context, id int64) (*PublicKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/keys/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result PublicKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserCurrentListFollowers — List the authenticated user's followers
// GET /user/followers
func (s *MiscService) UserCurrentListFollowers(ctx context.Context, page int, limit int) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/followers"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserCurrentListFollowing — List the users that the authenticated user is following
// GET /user/following
func (s *MiscService) UserCurrentListFollowing(ctx context.Context, page int, limit int) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/following"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserCurrentListGPGKeys — List the authenticated user's GPG keys
// GET /user/gpg_keys
func (s *MiscService) UserCurrentListGPGKeys(ctx context.Context, page int, limit int) ([]GPGKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/gpg_keys"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []GPGKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserCurrentListKeys — List the authenticated user's public keys
// GET /user/keys
func (s *MiscService) UserCurrentListKeys(ctx context.Context, fingerprint string, page int, limit int) ([]PublicKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/keys"))
	qry := u.Query()
	if fingerprint != "" { qry.Set("fingerprint", fmt.Sprintf("fingerprint", %!s(MISSING))) }
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []PublicKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserCurrentListRepos — List the repos that the authenticated user owns
// GET /user/repos
func (s *MiscService) UserCurrentListRepos(ctx context.Context, page int, limit int, orderBy string) ([]Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/repos"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	if orderBy != "" { qry.Set("order_by", fmt.Sprintf("orderBy", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserCurrentListStarred — The repos that the authenticated user has starred
// GET /user/starred
func (s *MiscService) UserCurrentListStarred(ctx context.Context, page int, limit int) ([]Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/starred"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserCurrentListSubscriptions — List repositories watched by the authenticated user
// GET /user/subscriptions
func (s *MiscService) UserCurrentListSubscriptions(ctx context.Context, page int, limit int) ([]Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/subscriptions"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserCurrentPostGPGKey — Add a GPG public key to current user's account
// POST /user/gpg_keys
func (s *MiscService) UserCurrentPostGPGKey(ctx context.Context, form *CreateGPGKeyOption) (*GPGKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/gpg_keys"))
	bodyBytes, err := json.Marshal(form)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result GPGKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserCurrentPostKey — Create a public key
// POST /user/keys
func (s *MiscService) UserCurrentPostKey(ctx context.Context, body *CreateKeyOption) (*PublicKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/keys"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result PublicKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserCurrentPutFollow — Follow a user
// PUT /user/following/{username}
func (s *MiscService) UserCurrentPutFollow(ctx context.Context, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/following/%s", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentPutStar — Star the given repo
// PUT /user/starred/{owner}/{repo}
func (s *MiscService) UserCurrentPutStar(ctx context.Context, owner string, repo string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/starred/%s/%s", owner, repo))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserCurrentTrackedTimes — List the current user's tracked times
// GET /user/times
func (s *MiscService) UserCurrentTrackedTimes(ctx context.Context, page int, limit int, since time.Time, before time.Time) ([]TrackedTime, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/times"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	if since != (time.Time{}) { qry.Set("since", fmt.Sprintf("since", %!s(MISSING))) }
	if before != (time.Time{}) { qry.Set("before", fmt.Sprintf("before", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []TrackedTime
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserDeleteAvatar — Delete avatar of the current user. It will be replaced by a default one
// DELETE /user/avatar
func (s *MiscService) UserDeleteAvatar(ctx context.Context) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/avatar"))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserDeleteEmail — Delete email addresses from the current user's account
// DELETE /user/emails
func (s *MiscService) UserDeleteEmail(ctx context.Context, body *DeleteEmailOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/emails"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserDeleteHook — Delete a hook
// DELETE /user/hooks/{id}
func (s *MiscService) UserDeleteHook(ctx context.Context, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/hooks/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserDeleteOAuth2Application — Delete an OAuth2 application
// DELETE /user/applications/oauth2/{id}
func (s *MiscService) UserDeleteOAuth2Application(ctx context.Context, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/applications/oauth2/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserEditHook — Update a hook
// PATCH /user/hooks/{id}
func (s *MiscService) UserEditHook(ctx context.Context, id int64, body *EditHookOption) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/hooks/%d", id))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserGetCurrent — Get the authenticated user
// GET /user
func (s *MiscService) UserGetCurrent(ctx context.Context) (*User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserGetHook — Get a hook
// GET /user/hooks/{id}
func (s *MiscService) UserGetHook(ctx context.Context, id int64) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/hooks/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserGetOAuth2Application — Get an OAuth2 application
// GET /user/applications/oauth2/{id}
func (s *MiscService) UserGetOAuth2Application(ctx context.Context, id int64) (*OAuth2Application, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/applications/oauth2/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result OAuth2Application
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserGetOAuth2Applications — List the authenticated user's oauth2 applications
// GET /user/applications/oauth2
func (s *MiscService) UserGetOAuth2Applications(ctx context.Context, page int, limit int) ([]OAuth2Application, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/applications/oauth2"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []OAuth2Application
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserGetQuota — Get quota information for the authenticated user
// GET /user/quota
func (s *MiscService) UserGetQuota(ctx context.Context) (*QuotaInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/quota"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result QuotaInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserGetRunnerRegistrationToken — Get the user's runner registration token
// GET /user/actions/runners/registration-token
func (s *MiscService) UserGetRunnerRegistrationToken(ctx context.Context) (*RegistrationToken, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/runners/registration-token"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result RegistrationToken
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserGetStopWatches — Get list of all existing stopwatches
// GET /user/stopwatches
func (s *MiscService) UserGetStopWatches(ctx context.Context, page int, limit int) ([]StopWatch, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/stopwatches"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []StopWatch
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserListBlockedUsers — List the authenticated user's blocked users
// GET /user/list_blocked
func (s *MiscService) UserListBlockedUsers(ctx context.Context, page int, limit int) ([]BlockedUser, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/list_blocked"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []BlockedUser
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserListEmails — List all email addresses of the current user
// GET /user/emails
func (s *MiscService) UserListEmails(ctx context.Context) ([]Email, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/emails"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Email
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserListHooks — List the authenticated user's webhooks
// GET /user/hooks
func (s *MiscService) UserListHooks(ctx context.Context, page int, limit int) ([]Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/hooks"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserListQuotaArtifacts — List the artifacts affecting the authenticated user's quota
// GET /user/quota/artifacts
func (s *MiscService) UserListQuotaArtifacts(ctx context.Context, page int, limit int) (*QuotaUsedArtifactList, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/quota/artifacts"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result QuotaUsedArtifactList
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserListQuotaAttachments — List the attachments affecting the authenticated user's quota
// GET /user/quota/attachments
func (s *MiscService) UserListQuotaAttachments(ctx context.Context, page int, limit int) (*QuotaUsedAttachmentList, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/quota/attachments"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result QuotaUsedAttachmentList
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserListQuotaPackages — List the packages affecting the authenticated user's quota
// GET /user/quota/packages
func (s *MiscService) UserListQuotaPackages(ctx context.Context, page int, limit int) (*QuotaUsedPackageList, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/quota/packages"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result QuotaUsedPackageList
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserListTeams — List all the teams a user belongs to
// GET /user/teams
func (s *MiscService) UserListTeams(ctx context.Context, page int, limit int) ([]Team, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/teams"))
	qry := u.Query()
	if page != 0 { qry.Set("page", fmt.Sprintf("page", %!s(MISSING))) }
	if limit != 0 { qry.Set("limit", fmt.Sprintf("limit", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []Team
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserSearchRunJobs — Search for user's action jobs according filter conditions
// GET /user/actions/runners/jobs
func (s *MiscService) UserSearchRunJobs(ctx context.Context, labels string) ([]ActionRunJob, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/actions/runners/jobs"))
	qry := u.Query()
	if labels != "" { qry.Set("labels", fmt.Sprintf("labels", %!s(MISSING))) }
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result []ActionRunJob
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil, nil, fmt.Errorf("decode: %w", err) }
	return result, &Response{Response: resp}, nil
}

// UserUnblockUser — Unblocks a user from the doer
// PUT /user/unblock/{username}
func (s *MiscService) UserUnblockUser(ctx context.Context, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/unblock/%s", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserUpdateAvatar — Update avatar of the current user
// POST /user/avatar
func (s *MiscService) UserUpdateAvatar(ctx context.Context, body *UpdateUserAvatarOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/avatar"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, handleError(resp) }

	return &Response{Response: resp}, nil
}

// UserUpdateOAuth2Application — Update an OAuth2 application, this includes regenerating the client secret
// PATCH /user/applications/oauth2/{id}
func (s *MiscService) UserUpdateOAuth2Application(ctx context.Context, id int64, body *CreateOAuth2ApplicationOptions) (*OAuth2Application, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/applications/oauth2/%d", id))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result OAuth2Application
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

// UserVerifyGPGKey — Verify a GPG key
// POST /user/gpg_key_verify
func (s *MiscService) UserVerifyGPGKey(ctx context.Context, body *VerifyGPGKeyOption) (*GPGKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/user/gpg_key_verify"))
	bodyBytes, err := json.Marshal(body)
	if err != nil { return nil, nil, fmt.Errorf("marshal: %w", err) }
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil { return nil, nil, fmt.Errorf("request: %w", err) }

	resp, err := s.client.client.Do(req)
	if err != nil { return nil, nil, fmt.Errorf("do: %w", err) }
	defer resp.Body.Close()

	if resp.StatusCode >= 400 { return nil, nil, handleError(resp) }

	var result GPGKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil { return nil,  nil, fmt.Errorf("decode: %w", err) }
	return &result, &Response{Response: resp}, nil
}

