// Code generated by api/gen. DO NOT EDIT.

package forgejo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// AdminAddRuleToQuotaGroup — Adds a rule to a quota group
// PUT /admin/quota/groups/{quotagroup}/rules/{quotarule}
func (s *AdminService) AdminAddRuleToQuotaGroup(ctx context.Context, quotagroup string, quotarule string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups/%s/rules/%s", quotagroup, quotarule))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminAddUserToQuotaGroup — Add a user to a quota group
// PUT /admin/quota/groups/{quotagroup}/users/{username}
func (s *AdminService) AdminAddUserToQuotaGroup(ctx context.Context, quotagroup string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups/%s/users/%s", quotagroup, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminAdoptRepository — Adopt unadopted files as a repository
// POST /admin/unadopted/{owner}/{repo}
func (s *AdminService) AdminAdoptRepository(ctx context.Context, owner string, repo string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/unadopted/%s/%s", owner, repo))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminCreateHook — Create a hook
// POST /admin/hooks
func (s *AdminService) AdminCreateHook(ctx context.Context, body *CreateHookOption) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/hooks"))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminCreateOrg — Create an organization
// POST /admin/users/{username}/orgs
func (s *AdminService) AdminCreateOrg(ctx context.Context, username string, organization *CreateOrgOption) (*Organization, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/orgs", username))
	bodyBytes, err := json.Marshal(organization)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result Organization
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminCreatePublicKey — Add an SSH public key to user's account
// POST /admin/users/{username}/keys
func (s *AdminService) AdminCreatePublicKey(ctx context.Context, username string, key *CreateKeyOption) (*PublicKey, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/keys", username))
	bodyBytes, err := json.Marshal(key)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result PublicKey
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminCreateQuotaGroup — Create a new quota group
// POST /admin/quota/groups
func (s *AdminService) AdminCreateQuotaGroup(ctx context.Context, group *CreateQuotaGroupOptions) (*QuotaGroup, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups"))
	bodyBytes, err := json.Marshal(group)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result QuotaGroup
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminCreateQuotaRule — Create a new quota rule
// POST /admin/quota/rules
func (s *AdminService) AdminCreateQuotaRule(ctx context.Context, rule *CreateQuotaRuleOptions) (*QuotaRuleInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/rules"))
	bodyBytes, err := json.Marshal(rule)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result QuotaRuleInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminCreateRepo — Create a repository on behalf of a user
// POST /admin/users/{username}/repos
func (s *AdminService) AdminCreateRepo(ctx context.Context, username string, repository *CreateRepoOption) (*Repository, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/repos", username))
	bodyBytes, err := json.Marshal(repository)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result Repository
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminCreateUser — Create a user account
// POST /admin/users
func (s *AdminService) AdminCreateUser(ctx context.Context, body *CreateUserOption) (*User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users"))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminCreateUserAccessToken — Create an access token for the specified user
// POST /admin/users/{username}/tokens
func (s *AdminService) AdminCreateUserAccessToken(ctx context.Context, username string, body *CreateAccessTokenOption) (*AccessToken, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/tokens", username))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result AccessToken
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminCronList — List cron tasks
// GET /admin/cron
func (s *AdminService) AdminCronList(ctx context.Context, page int, limit int) ([]Cron, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/cron"))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Cron
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminCronRun — Run cron task
// POST /admin/cron/{task}
func (s *AdminService) AdminCronRun(ctx context.Context, task string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/cron/%s", task))
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminDeleteHook — Delete a hook
// DELETE /admin/hooks/{id}
func (s *AdminService) AdminDeleteHook(ctx context.Context, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/hooks/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminDeleteQuotaGroup — Delete a quota group
// DELETE /admin/quota/groups/{quotagroup}
func (s *AdminService) AdminDeleteQuotaGroup(ctx context.Context, quotagroup string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups/%s", quotagroup))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminDeleteQuotaRule — Deletes a quota rule
// DELETE /admin/quota/rules/{quotarule}
func (s *AdminService) AdminDeleteQuotaRule(ctx context.Context, quotarule string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/rules/%s", quotarule))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminDeleteUnadoptedRepository — Delete unadopted files
// DELETE /admin/unadopted/{owner}/{repo}
func (s *AdminService) AdminDeleteUnadoptedRepository(ctx context.Context, owner string, repo string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/unadopted/%s/%s", owner, repo))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminDeleteUser — Delete user account
// DELETE /admin/users/{username}
func (s *AdminService) AdminDeleteUser(ctx context.Context, username string, purge bool) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s", username))
	qry := u.Query()
	if purge != false {
		qry.Set("purge", fmt.Sprintf("%v", purge))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminDeleteUserAccessToken — Delete an access token for the specified user
// DELETE /admin/users/{username}/tokens/{token}
func (s *AdminService) AdminDeleteUserAccessToken(ctx context.Context, username string, token string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/tokens/%s", username, token))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminDeleteUserEmails — Delete email addresses from a user's account
// DELETE /admin/users/{username}/emails
func (s *AdminService) AdminDeleteUserEmails(ctx context.Context, username string, body *DeleteEmailOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/emails", username))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminDeleteUserPublicKey — Remove a public key from user's account
// DELETE /admin/users/{username}/keys/{id}
func (s *AdminService) AdminDeleteUserPublicKey(ctx context.Context, username string, id int64) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/keys/%d", username, id))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminEditHook — Update a hook
// PATCH /admin/hooks/{id}
func (s *AdminService) AdminEditHook(ctx context.Context, id int64, body *EditHookOption) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/hooks/%d", id))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminEditQuotaRule — Change an existing quota rule
// PATCH /admin/quota/rules/{quotarule}
func (s *AdminService) AdminEditQuotaRule(ctx context.Context, quotarule string, rule *EditQuotaRuleOptions) (*QuotaRuleInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/rules/%s", quotarule))
	bodyBytes, err := json.Marshal(rule)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result QuotaRuleInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminEditUser — Edit an existing user
// PATCH /admin/users/{username}
func (s *AdminService) AdminEditUser(ctx context.Context, username string, body *EditUserOption) (*User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s", username))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminGetActionRunJobs — Get action run jobs
// GET /admin/actions/runners/jobs
func (s *AdminService) AdminGetActionRunJobs(ctx context.Context, labels string) ([]ActionRunJob, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/actions/runners/jobs"))
	qry := u.Query()
	if labels != "" {
		qry.Set("labels", fmt.Sprintf("%v", labels))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []ActionRunJob
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminGetAllEmails — List all users' email addresses
// GET /admin/emails
func (s *AdminService) AdminGetAllEmails(ctx context.Context, page int, limit int) ([]Email, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/emails"))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Email
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminGetAllOrgs — List all organizations
// GET /admin/orgs
func (s *AdminService) AdminGetAllOrgs(ctx context.Context, page int, limit int) ([]Organization, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/orgs"))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Organization
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminGetHook — Get a hook
// GET /admin/hooks/{id}
func (s *AdminService) AdminGetHook(ctx context.Context, id int64) (*Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/hooks/%d", id))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminGetQuotaGroup — Get information about the quota group
// GET /admin/quota/groups/{quotagroup}
func (s *AdminService) AdminGetQuotaGroup(ctx context.Context, quotagroup string) (*QuotaGroup, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups/%s", quotagroup))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result QuotaGroup
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminGetQuotaRule — Get information about a quota rule
// GET /admin/quota/rules/{quotarule}
func (s *AdminService) AdminGetQuotaRule(ctx context.Context, quotarule string) (*QuotaRuleInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/rules/%s", quotarule))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result QuotaRuleInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminGetRegistrationToken — Get a runner registration token for registering global runners
// GET /admin/runners/registration-token
func (s *AdminService) AdminGetRegistrationToken(ctx context.Context) (*RegistrationToken, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/runners/registration-token"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result RegistrationToken
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminGetRunnerRegistrationToken — Get a runner registration token for registering global runners
// GET /admin/actions/runners/registration-token
func (s *AdminService) AdminGetRunnerRegistrationToken(ctx context.Context) (*RegistrationToken, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/actions/runners/registration-token"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result RegistrationToken
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminGetUserQuota — Get the user's quota info
// GET /admin/users/{username}/quota
func (s *AdminService) AdminGetUserQuota(ctx context.Context, username string) (*QuotaInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/quota", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result QuotaInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminListHooks — List global (system) webhooks
// GET /admin/hooks
func (s *AdminService) AdminListHooks(ctx context.Context, page int, limit int) ([]Hook, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/hooks"))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Hook
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminListQuotaGroups — List the available quota groups
// GET /admin/quota/groups
func (s *AdminService) AdminListQuotaGroups(ctx context.Context) (*QuotaGroupList, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result QuotaGroupList
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// AdminListQuotaRules — List the available quota rules
// GET /admin/quota/rules
func (s *AdminService) AdminListQuotaRules(ctx context.Context) ([]QuotaRuleInfo, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/rules"))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []QuotaRuleInfo
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminListUserAccessTokens — List the specified user's access tokens
// GET /admin/users/{username}/tokens
func (s *AdminService) AdminListUserAccessTokens(ctx context.Context, username string, page int, limit int) ([]AccessToken, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/tokens", username))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []AccessToken
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminListUserEmails — List all email addresses for a user
// GET /admin/users/{username}/emails
func (s *AdminService) AdminListUserEmails(ctx context.Context, username string) ([]Email, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/emails", username))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Email
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminListUsersInQuotaGroup — List users in a quota group
// GET /admin/quota/groups/{quotagroup}/users
func (s *AdminService) AdminListUsersInQuotaGroup(ctx context.Context, quotagroup string) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups/%s/users", quotagroup))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminRemoveRuleFromQuotaGroup — Removes a rule from a quota group
// DELETE /admin/quota/groups/{quotagroup}/rules/{quotarule}
func (s *AdminService) AdminRemoveRuleFromQuotaGroup(ctx context.Context, quotagroup string, quotarule string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups/%s/rules/%s", quotagroup, quotarule))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminRemoveUserFromQuotaGroup — Remove a user from a quota group
// DELETE /admin/quota/groups/{quotagroup}/users/{username}
func (s *AdminService) AdminRemoveUserFromQuotaGroup(ctx context.Context, quotagroup string, username string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/quota/groups/%s/users/%s", quotagroup, username))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminRenameUser — Rename a user
// POST /admin/users/{username}/rename
func (s *AdminService) AdminRenameUser(ctx context.Context, username string, body *RenameUserOption) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/rename", username))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminSearchEmails — Search users' email addresses
// GET /admin/emails/search
func (s *AdminService) AdminSearchEmails(ctx context.Context, q string, page int, limit int) ([]Email, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/emails/search"))
	qry := u.Query()
	if q != "" {
		qry.Set("q", fmt.Sprintf("%v", q))
	}
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []Email
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminSearchRunJobs — Search action jobs according to filter conditions
// GET /admin/runners/jobs
func (s *AdminService) AdminSearchRunJobs(ctx context.Context, labels string) ([]ActionRunJob, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/runners/jobs"))
	qry := u.Query()
	if labels != "" {
		qry.Set("labels", fmt.Sprintf("%v", labels))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []ActionRunJob
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminSearchUsers — Search users according filter conditions
// GET /admin/users
func (s *AdminService) AdminSearchUsers(ctx context.Context, sourceId int64, loginName string, is2faEnabled bool, sort string, page int, limit int) ([]User, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users"))
	qry := u.Query()
	if sourceId != 0 {
		qry.Set("source_id", fmt.Sprintf("%v", sourceId))
	}
	if loginName != "" {
		qry.Set("login_name", fmt.Sprintf("%v", loginName))
	}
	if is2faEnabled != false {
		qry.Set("is_2fa_enabled", fmt.Sprintf("%v", is2faEnabled))
	}
	if sort != "" {
		qry.Set("sort", fmt.Sprintf("%v", sort))
	}
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []User
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// AdminSetUserQuotaGroups — Set the user's quota groups to a given list.
// POST /admin/users/{username}/quota/groups
func (s *AdminService) AdminSetUserQuotaGroups(ctx context.Context, username string, groups *SetUserQuotaGroupsOptions) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/users/%s/quota/groups", username))
	bodyBytes, err := json.Marshal(groups)
	if err != nil {
		return nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// AdminUnadoptedList — List unadopted repositories
// GET /admin/unadopted
func (s *AdminService) AdminUnadoptedList(ctx context.Context, page int, limit int, pattern string) ([]string, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/unadopted"))
	qry := u.Query()
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	if pattern != "" {
		qry.Set("pattern", fmt.Sprintf("%v", pattern))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []string
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// DeleteAdminRunner — Delete a particular runner, no matter whether it is a global runner or scoped to an organization, user, or repository
// DELETE /admin/actions/runners/{runner_id}
func (s *AdminService) DeleteAdminRunner(ctx context.Context, runnerId string) (*Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/actions/runners/%s", runnerId))
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, handleError(resp)
	}

	return &Response{Response: resp}, nil
}

// GetAdminRunner — Get a particular runner, no matter whether it is a global runner or scoped to an organization, user, or repository
// GET /admin/actions/runners/{runner_id}
func (s *AdminService) GetAdminRunner(ctx context.Context, runnerId string) (*ActionRunner, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/actions/runners/%s", runnerId))
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result ActionRunner
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}

// GetAdminRunners — Get all runners, no matter whether they are global runners or scoped to an organization, user, or repository
// GET /admin/actions/runners
func (s *AdminService) GetAdminRunners(ctx context.Context, visible bool, page int, limit int) ([]ActionRunner, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/actions/runners"))
	qry := u.Query()
	if visible != false {
		qry.Set("visible", fmt.Sprintf("%v", visible))
	}
	if page != 0 {
		qry.Set("page", fmt.Sprintf("%v", page))
	}
	if limit != 0 {
		qry.Set("limit", fmt.Sprintf("%v", limit))
	}
	u.RawQuery = qry.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result []ActionRunner
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return result, &Response{Response: resp}, nil
}

// RegisterAdminRunner — Register a new global runner
// POST /admin/actions/runners
func (s *AdminService) RegisterAdminRunner(ctx context.Context, body *RegisterRunnerOptions) (*RegisterRunnerResponse, *Response, error) {
	u := s.client.base.JoinPath(fmt.Sprintf("/admin/actions/runners"))
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(bodyBytes))
	req.Header.Set("Content-Type", "application/json")
	if err != nil {
		return nil, nil, fmt.Errorf("request: %w", err)
	}

	resp, err := s.client.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return nil, nil, handleError(resp)
	}

	var result RegisterRunnerResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, nil, fmt.Errorf("decode: %w", err)
	}
	return &result, &Response{Response: resp}, nil
}
