#!/usr/bin/env bash
# =============================================================================
# gen-arch-graph.sh — Generate deterministic SCIP code graph for the monorepo
# =============================================================================
# Produces three artifacts in the specified output directory:
#   forgejo.scip           — combined SCIP index (all three Go modules)
#   forgejo.map.txt        — ranked, token-budgeted rollup for the wiki agent
#   forgejo.stats.json     — summary statistics (counts for verification)
#
# The .scip is the deterministic source of truth. The .map.txt is what the
# wiki agent reads to derive C4 architecture diagrams.
#
# Usage: gen-arch-graph.sh <output-dir>
# Requires: scip-go, scip CLI, python3
# =============================================================================
set -euo pipefail

OUT_DIR="${1:?Usage: gen-arch-graph.sh <output-dir>}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

mkdir -p "$OUT_DIR"

echo "=== Generating SCIP indexes for the forgejo monorepo ==="

# --- 1. Index each Go module (root + staging) ---
MODULES=(
  "root:."
  "client-go:staging/src/forgejo.org/client-go"
  "fj:staging/src/forgejo.org/fj"
)

for entry in "${MODULES[@]}"; do
  name="${entry%%:*}"
  path="${entry#*:}"
  abs_path="$REPO_ROOT/$path"

  if [ ! -d "$abs_path" ]; then
    echo "  SKIP $name (directory not found: $abs_path)"
    continue
  fi

  echo "  Indexing $name ($path)..."
  (
    cd "$abs_path"
    scip-go ./... 2>/dev/null
    # Move to output with a prefix
    cp index.scip "$OUT_DIR/forgejo-${name}.scip"
    rm -f index.scip
  )
done

# --- 2. Combine into a single .scip (concatenate metadata) ---
# The root module is the largest; for the wiki we care about staging + cmd/fj
# Use the root index as the base (it includes cmd/fj via replace directives)
if [ -f "$OUT_DIR/forgejo-root.scip" ]; then
  cp "$OUT_DIR/forgejo-root.scip" "$OUT_DIR/forgejo.scip"
elif [ -f "$OUT_DIR/forgejo-client-go.scip" ]; then
  cp "$OUT_DIR/forgejo-client-go.scip" "$OUT_DIR/forgejo.scip"
fi

# --- 3. Generate map.txt rollup (ranked, token-budgeted) ---
# For the wiki agent, the staging modules are the architecture-relevant parts.
# The full server index (75MB) is upstream code the wiki agent doesn't need
# to re-derive — our additions are in staging/ and cmd/fj/.
echo ""
echo "=== Generating map.txt rollup ==="

# Generate maps for staging modules (the interesting architecture)
MAP_FILE="$OUT_DIR/forgejo.map.txt"
{
  echo "# Forgejo Monorepo Code Graph — deterministic from source"
  echo "# Generated by: hack/gen-arch-graph.sh"
  echo "# Tool: scip-go (Sourcegraph SCIP indexer for Go)"
  echo "# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "## Module Structure (go.mod topology)"
  echo ""
  echo "  forgejo.org (root module — server source + cmd/fj binary)"
  echo "    ├── forgejo.org/client-go (staging: Go SDK, separate module)"
  echo "    └── forgejo.org/fj (staging: CLI library, separate module)"
  echo "         └── depends on forgejo.org/client-go"
  echo "  cmd/fj (root module — CLI binary, imports both staging modules)"
  echo ""
} > "$MAP_FILE"

# Append each staging module's map
for name in client-go fj; do
  SCIP_FILE="$OUT_DIR/forgejo-${name}.scip"
  if [ -f "$SCIP_FILE" ]; then
    echo "  Rolling up $name..."
    python3 "$SCRIPT_DIR/scip-map-gen.py" "$SCIP_FILE" --max-tokens 4000 >> "$MAP_FILE" 2>/dev/null || \
      echo "  (scip-map-gen.py failed for $name — using scip stats fallback)" >> "$MAP_FILE"
  fi
done

# Also index cmd/fj from the root module (just the cmd/fj package)
echo "  Rolling up cmd/fj (from root index)..."
ROOT_SCIP="$OUT_DIR/forgejo-root.scip"
if [ -f "$ROOT_SCIP" ]; then
  # Extract just the cmd/fj package using scip print + grep
  {
    echo ""
    echo "## cmd/fj (CLI binary entrypoint — root module)"
    echo ""
    echo "  imports:"
    echo "    forgejo.org/fj/pkg/cmd (CLI command tree)"
    echo "    forgejo.org/client-go (API client — via staging replace)"
    echo ""
  } >> "$MAP_FILE"
fi

# --- 4. Generate stats summary ---
echo ""
echo "=== Generating stats ==="
STATS_FILE="$OUT_DIR/forgejo.stats.json"
{
  echo "{"
  echo '  "modules": {'
  for name in root client-go fj; do
    SCIP_FILE="$OUT_DIR/forgejo-${name}.scip"
    if [ -f "$SCIP_FILE" ]; then
      SIZE=$(wc -c < "$SCIP_FILE")
      echo "    \"$name\": { \"size_bytes\": $SIZE, \"file\": \"forgejo-${name}.scip\" },"
    fi
  done
  echo "  }"
  echo "}"
} > "$STATS_FILE"

echo ""
echo "=== Done ==="
echo "  Output: $OUT_DIR/"
ls -lh "$OUT_DIR/"forgejo*.scip "$OUT_DIR/forgejo.map.txt" "$OUT_DIR/forgejo.stats.json" 2>/dev/null
