#!/usr/bin/env bash
# =============================================================================
# gen-arch-graph.sh — Generate deterministic SCIP code graph for the monorepo
# =============================================================================
# Produces SCIP indexes + a ranked map.txt rollup in docs/arch/.
# The map.txt is what the wiki agent reads to derive C4 architecture diagrams.
#
# Run automatically by the post-merge hook after SDK/CLI regen, so the sync
# PR always carries a graph that matches the code.
#
# Usage: gen-arch-graph.sh
# Requires: scip-go (installed at runtime if missing)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$REPO_ROOT/docs/arch"

mkdir -p "$OUT_DIR"

# --- 0. Ensure scip-go is installed ---
if ! command -v scip-go >/dev/null 2>&1; then
  echo "[arch-graph] installing scip-go..."
  go install github.com/sourcegraph/scip-go/cmd/scip-go@latest 2>/dev/null || true
  export PATH="$HOME/go/bin:$PATH"
fi

if ! command -v scip-go >/dev/null 2>&1; then
  echo "[arch-graph] WARNING: scip-go not available — skipping graph generation"
  exit 0
fi

echo "[arch-graph] generating SCIP indexes..."

# --- 1. Index staging modules (the architecture-relevant parts) ---
MODULES=(
  "client-go:staging/src/forgejo.org/client-go"
  "fj:staging/src/forgejo.org/fj"
)

for entry in "${MODULES[@]}"; do
  name="${entry%%:*}"
  path="${entry#*:}"
  abs_path="$REPO_ROOT/$path"

  if [ ! -d "$abs_path" ]; then
    echo "[arch-graph]   SKIP $name (not found)"
    continue
  fi

  echo "[arch-graph]   indexing $name..."
  (
    cd "$abs_path"
    scip-go ./... 2>/dev/null
    mv index.scip "$OUT_DIR/forgejo-${name}.scip" 2>/dev/null || true
  )
done

# --- 2. Generate map.txt rollup ---
echo "[arch-graph] generating map.txt..."
MAP_FILE="$OUT_DIR/forgejo.map.txt"

{
  echo "# Forgejo Monorepo Code Graph — deterministic from source"
  echo "# Generated by: hack/gen-arch-graph.sh"
  echo "# Tool: scip-go (Sourcegraph SCIP indexer for Go)"
  echo "# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "## Module Structure (go.mod topology)"
  echo ""
  echo "  forgejo.org (root module — server source + cmd/fj binary)"
  echo "    ├── forgejo.org/client-go (staging: Go SDK, separate module)"
  echo "    └── forgejo.org/fj (staging: CLI library, separate module)"
  echo "         └── depends on forgejo.org/client-go"
  echo "  cmd/fj (root module — CLI binary, imports both staging modules)"
  echo ""
} > "$MAP_FILE"

for name in client-go fj; do
  SCIP_FILE="$OUT_DIR/forgejo-${name}.scip"
  if [ -f "$SCIP_FILE" ] && [ -f "$SCRIPT_DIR/scip-map-gen.py" ]; then
    echo "[arch-graph]   rolling up $name..."
    python3 "$SCRIPT_DIR/scip-map-gen.py" "$SCIP_FILE" --max-tokens 4000 >> "$MAP_FILE" 2>/dev/null || \
      echo "[arch-graph]   WARNING: map-gen failed for $name" >> "$MAP_FILE"
  fi
done

echo "[arch-graph] done: $OUT_DIR/"
ls -lh "$OUT_DIR/"forgejo*.scip "$MAP_FILE" 2>/dev/null
