// (no build tag) — this test needs no live instance. It is a fast codegen/spec
// gate: it reads client-go/spec/swagger.json and parses `fj --help` to verify
// the hand-written UX commands are (a) mapped to real operationIds and
// (b) actually implemented. Runnable in any CI context.
//
// This is the machine-checked definition of "fj parity with the Rust
// forgejo-cli". When upstream renames/removes an operationId, this test fails
// and names the affected fj command — the monorepo automation payoff.
//
// The contract itself is GENERATED by the swagger generator (gen/parity.yaml
// -> pkg/cmd/zz_generated_parity.go, see issue #03), so spec drift is caught
// at generation time too; this test catches drift in any context that ships
// the generated map without regenerating.
package integration

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	fjcmd "forgejo.org/fj/pkg/cmd"
)

// expectedUXCommands is the GENERATED parity contract emitted by the swagger
// generator from gen/parity.yaml (pkg/cmd/zz_generated_parity.go, issue #03).
// Hand-maintenance moved out of the test into the generator so the contract is
// regenerated from the spec automatically.
var expectedUXCommands = fjcmd.CommandToOperation

// swaggerSpecPath resolves the swagger.json that the SDK was generated from,
// relative to this test file.
func swaggerSpecPath(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	// .../fj/tests/integration/parity_inventory_test.go
	// swagger.json at .../client-go/spec/swagger.json
	candidates := []string{
		// .../fj/tests/integration -> .../forgejo.org/client-go/spec/swagger.json
		filepath.Join(filepath.Dir(file), "..", "..", "..", "client-go", "spec", "swagger.json"),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c
		}
	}
	t.Skipf("swagger.json not found near %s", filepath.Dir(file))
	return ""
}

// loadOperationIDs reads swagger.json and returns the set of operationIds.
func loadOperationIDs(t *testing.T, specPath string) map[string]bool {
	t.Helper()
	raw, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatalf("read swagger.json: %v", err)
	}
	var spec struct {
		Paths map[string]map[string]struct {
			OperationID string `json:"operationId"`
		} `json:"paths"`
	}
	if err := json.Unmarshal(raw, &spec); err != nil {
		t.Fatalf("parse swagger.json: %v", err)
	}
	ops := map[string]bool{}
	for _, methods := range spec.Paths {
		for method, op := range methods {
			if strings.EqualFold(method, "parameters") {
				continue
			}
			if op.OperationID != "" {
				ops[op.OperationID] = true
			}
		}
	}
	if len(ops) == 0 {
		t.Fatal("swagger.json has no operationIds — parser broken?")
	}
	return ops
}

// discoverFJCommands builds the fj binary and returns the set of top-level
// commands (issue, pr, repo, ...) and, for each expected group, its
// subcommands (issue: create/view/list/...). The set is keyed "group" and
// "group subverb".
func discoverFJCommands(t *testing.T) map[string]bool {
	t.Helper()
	binary := buildFjBinary(t)

	// Discover top-level commands from `fj --help`.
	help := func(args ...string) string {
		t.Helper()
		out, err := exec.Command(binary, args...).CombinedOutput()
		if err != nil {
			t.Logf("fj %v: %v\n%s", args, err, out)
		}
		return string(out)
	}

	cmds := map[string]bool{}
	// Cobra help lists commands indented under "Available Commands:".
	for _, line := range strings.Split(help("--help"), "\n") {
		// lines look like "  issue        Manage issues"
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "-") || strings.Contains(line, "Available Commands") {
			continue
		}
		fields := strings.Fields(trimmed)
		if len(fields) >= 1 {
			cmds[fields[0]] = true
		}
	}

	// For each expected group, discover subverbs.
	groups := map[string]bool{}
	for k := range expectedUXCommands {
		parts := strings.Fields(k)
		groups[parts[0]] = true
	}
	for g := range groups {
		if !cmds[g] {
			continue // group missing — recorded as a gap below
		}
		for _, line := range strings.Split(help(g, "--help"), "\n") {
			trimmed := strings.TrimSpace(line)
			if trimmed == "" || strings.HasPrefix(trimmed, "-") || strings.Contains(line, "Available Commands") {
				continue
			}
			fields := strings.Fields(trimmed)
			if len(fields) >= 1 {
				cmds[g+" "+fields[0]] = true
			}
		}
	}
	return cmds
}

// TestParityInventory is the gap report. It FAILS when:
//   - a mapped operationId is absent from swagger.json (upstream drift), or
//   - an expected UX command is not implemented in fj (coverage gap).
//
// Both failures print the concrete list so the answer to "do we have parity?"
// is a build artifact, not prose.
func TestParityInventory(t *testing.T) {
	ops := loadOperationIDs(t, swaggerSpecPath(t))

	// --- Check 1: spec drift (mapped opId must exist in the spec) ---
	var specDrift []string
	for cmd, opID := range expectedUXCommands {
		if !ops[opID] {
			specDrift = append(specDrift, fmtDrift(cmd, opID))
		}
	}
	if len(specDrift) > 0 {
		sort.Strings(specDrift)
		t.Errorf("PARITY — spec drift: %d expected fj command(s) reference operationIds "+
			"that no longer exist in swagger.json (upstream renamed/removed them):\n  %s",
			len(specDrift), strings.Join(specDrift, "\n  "))
	}

	// --- Check 2: CLI coverage (expected command must be implemented) ---
	// Building the binary needs the repo root; skip coverage check if we
	// cannot build (e.g. running in a context without the full source tree).
	if !fjBinaryBuildable() {
		t.Skip("fj binary not buildable here — skipping CLI coverage check (spec drift only)")
	}
	implemented := discoverFJCommands(t)

	var missingCmds []string
	for cmd := range expectedUXCommands {
		parts := strings.Fields(cmd)
		if len(parts) == 1 {
			// top-level command (whoami, version)
			if !implemented[parts[0]] {
				missingCmds = append(missingCmds, cmd)
			}
			continue
		}
		// "group verb"
		if !implemented[parts[0]+" "+parts[1]] {
			missingCmds = append(missingCmds, cmd)
		}
	}
	if len(missingCmds) > 0 {
		sort.Strings(missingCmds)
		t.Errorf("PARITY — coverage gap: %d expected fj UX command(s) are not implemented "+
			"(parity with the Rust forgejo-cli):\n  %s",
			len(missingCmds), strings.Join(missingCmds, "\n  "))
	}

	if len(specDrift) == 0 && len(missingCmds) == 0 {
		t.Logf("PARITY OK: %d expected commands mapped and implemented, %d operationIds in spec",
			len(expectedUXCommands), len(ops))
	}
}

// fjBinaryBuildable reports whether the fj binary can be built in this context
// (the full repo source tree is present). Cheap pre-check so the spec-drift
// half of the test still runs even when the binary can't be built.
func fjBinaryBuildable() bool {
	root := repoRoot()
	if root == "" {
		return false
	}
	_, err := os.Stat(filepath.Join(root, "cmd", "fj", "fj.go"))
	return err == nil
}

// repoRoot returns the forgejo.org root module dir, mirroring buildFjBinary's
// discovery (env FORGEJO_REPO_ROOT, else walk up for cmd/fj).
func repoRoot() string {
	if r := os.Getenv("FORGEJO_REPO_ROOT"); r != "" {
		return r
	}
	dir, _ := os.Getwd()
	for i := 0; i < 12; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			if _, err := os.Stat(filepath.Join(dir, "cmd", "fj")); err == nil {
				return dir
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return ""
}

// fmtDrift formats a spec-drift finding for the failure message.
func fmtDrift(cmd, opID string) string {
	return cmd + " -> " + opID + "  [MISSING from swagger.json]"
}
