// Code generated by mockery v2.53.5. DO NOT EDIT.

package container

import (
	context "context"

	common "code.forgejo.org/forgejo/runner/v12/act/common"

	io "io"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockContainer is an autogenerated mock type for the Container type
type MockContainer struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockContainer) Close() common.Executor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func() common.Executor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// ConnectToNetwork provides a mock function with given fields: name
func (_m *MockContainer) ConnectToNetwork(name string) common.Executor {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ConnectToNetwork")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func(string) common.Executor); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// Copy provides a mock function with given fields: destPath, files
func (_m *MockContainer) Copy(destPath string, files ...*FileEntry) common.Executor {
	_va := make([]interface{}, len(files))
	for _i := range files {
		_va[_i] = files[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, destPath)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func(string, ...*FileEntry) common.Executor); ok {
		r0 = rf(destPath, files...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// CopyDir provides a mock function with given fields: destPath, srcPath, useGitIgnore
func (_m *MockContainer) CopyDir(destPath string, srcPath string, useGitIgnore bool) common.Executor {
	ret := _m.Called(destPath, srcPath, useGitIgnore)

	if len(ret) == 0 {
		panic("no return value specified for CopyDir")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func(string, string, bool) common.Executor); ok {
		r0 = rf(destPath, srcPath, useGitIgnore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// CopyTarStream provides a mock function with given fields: ctx, destPath, tarStream
func (_m *MockContainer) CopyTarStream(ctx context.Context, destPath string, tarStream io.Reader) error {
	ret := _m.Called(ctx, destPath, tarStream)

	if len(ret) == 0 {
		panic("no return value specified for CopyTarStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, destPath, tarStream)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: capAdd, capDrop
func (_m *MockContainer) Create(capAdd []string, capDrop []string) common.Executor {
	ret := _m.Called(capAdd, capDrop)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func([]string, []string) common.Executor); ok {
		r0 = rf(capAdd, capDrop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// Exec provides a mock function with given fields: command, env, user, workdir
func (_m *MockContainer) Exec(command []string, env map[string]string, user string, workdir string) common.Executor {
	ret := _m.Called(command, env, user, workdir)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func([]string, map[string]string, string, string) common.Executor); ok {
		r0 = rf(command, env, user, workdir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// GetContainerArchive provides a mock function with given fields: ctx, srcPath
func (_m *MockContainer) GetContainerArchive(ctx context.Context, srcPath string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, srcPath)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerArchive")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, srcPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, srcPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, srcPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsHealthy provides a mock function with given fields: ctx
func (_m *MockContainer) IsHealthy(ctx context.Context) (time.Duration, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsHealthy")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (time.Duration, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) time.Duration); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Pull provides a mock function with given fields: forcePull
func (_m *MockContainer) Pull(forcePull bool) common.Executor {
	ret := _m.Called(forcePull)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func(bool) common.Executor); ok {
		r0 = rf(forcePull)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// Remove provides a mock function with no fields
func (_m *MockContainer) Remove() common.Executor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func() common.Executor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// ReplaceLogWriter provides a mock function with given fields: _a0, _a1
func (_m *MockContainer) ReplaceLogWriter(_a0 io.Writer, _a1 io.Writer) (io.Writer, io.Writer) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceLogWriter")
	}

	var r0 io.Writer
	var r1 io.Writer
	if rf, ok := ret.Get(0).(func(io.Writer, io.Writer) (io.Writer, io.Writer)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(io.Writer, io.Writer) io.Writer); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Writer, io.Writer) io.Writer); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.Writer)
		}
	}

	return r0, r1
}

// Start provides a mock function with given fields: attach
func (_m *MockContainer) Start(attach bool) common.Executor {
	ret := _m.Called(attach)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func(bool) common.Executor); ok {
		r0 = rf(attach)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// UpdateFromEnv provides a mock function with given fields: srcPath, env
func (_m *MockContainer) UpdateFromEnv(srcPath string, env *map[string]string) common.Executor {
	ret := _m.Called(srcPath, env)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFromEnv")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func(string, *map[string]string) common.Executor); ok {
		r0 = rf(srcPath, env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// UpdateFromImageEnv provides a mock function with given fields: env
func (_m *MockContainer) UpdateFromImageEnv(env *map[string]string) common.Executor {
	ret := _m.Called(env)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFromImageEnv")
	}

	var r0 common.Executor
	if rf, ok := ret.Get(0).(func(*map[string]string) common.Executor); ok {
		r0 = rf(env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Executor)
		}
	}

	return r0
}

// NewMockContainer creates a new instance of MockContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockContainer {
	mock := &MockContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
